#pragma once

#pragma region mrpc

#include <protocol/mrpc_table_load.h>
#include <protocol/mrpc_update_redis_rpcinfo.h>
#include <protocol/mrpc_channel_update_zoneinfo.h>
#include <protocol/mrpc_get_redis_rpcinfo.h>
#include <protocol/mrpc_update_redis_serverinfo.h>
#include <protocol/mrpc_connector_rpcinfo.h>
#include <protocol/mrpc_player_server_change.h>
#include <protocol/mrpc_action_log.h>
#include <protocol/mrpc_player_game_login.h>
#include <protocol/mrpc_game_balance.h>
#include <protocol/mrpc_exchange_register.h>
#include <protocol/mrpc_exchange_register_cancel.h>
#include <protocol/mrpc_exchange_buy.h>
#include <protocol/mrpc_exchange_gold_withdraw.h>
#include <protocol/mrpc_server_redirect.h>
#include <protocol/mrpc_indun_create.h>
#include <protocol/mrpc_community_info.h>
#include <protocol/mrpc_community_info2.h>
#include <protocol/mrpc_community_character_levelup.h>
#include <protocol/mrpc_community_character_level_info.h>
#include <protocol/mrpc_community_game_login.h>
#include <protocol/mrpc_community_zone_enter.h>
#include <protocol/mrpc_community_game_logoff.h>
#include <protocol/mrpc_community_character_game_login.h>
#include <protocol/mrpc_community_guild_member.h>
#include <protocol/mrpc_community_party_member.h>
#include <protocol/mrpc_community_social_motion.h>
#include <protocol/mrpc_community_object_run_time_update.h>
#include <protocol/mrpc_community_object_message.h>
#include <protocol/mrpc_game_event_info.h>
#include <protocol/mrpc_game_world_boss_spawn.h>
#include <protocol/mrpc_party_create.h>
#include <protocol/mrpc_party_destroy.h>
#include <protocol/mrpc_party_enter_request.h>
#include <protocol/mrpc_party_enter_cancel.h>
#include <protocol/mrpc_party_enter_agree.h>
#include <protocol/mrpc_party_leave.h>
#include <protocol/mrpc_party_leave_alert_by_indun_kick.h>
#include <protocol/mrpc_party_member_ban.h>
#include <protocol/mrpc_party_owner_change.h>
#include <protocol/mrpc_party_setup.h>
#include <protocol/mrpc_party_enter_refuse.h>
#include <protocol/mrpc_party_enter_request_list.h>
#include <protocol/mrpc_party_enter_requestors.h>
#include <protocol/mrpc_party_invite_request.h>
#include <protocol/mrpc_party_invite_agree.h>
#include <protocol/mrpc_party_invite_refuse.h>
#include <protocol/mrpc_game_login.h>
#include <protocol/mrpc_test_game_login.h>
#include <protocol/mrpc_character_redirect.h>
#include <protocol/mrpc_guild_create.h>
#include <protocol/mrpc_guild_destroy.h>
#include <protocol/mrpc_guild_join_request.h>
#include <protocol/mrpc_guild_accept_member.h>
#include <protocol/mrpc_guild_join_cancel.h>
#include <protocol/mrpc_guild_recommend.h>
#include <protocol/mrpc_guild_request_guild_list.h>
#include <protocol/mrpc_guild_info.h>
#include <protocol/mrpc_guild_ban.h>
#include <protocol/mrpc_guild_leave.h>
#include <protocol/mrpc_guild_change_member_grade.h>
#include <protocol/mrpc_guild_master_change_by_non_connected.h>
#include <protocol/mrpc_guild_change_nickname.h>
#include <protocol/mrpc_gameitem_update.h>
#include <protocol/mrpc_quest_finish.h>
#include <protocol/mrpc_gm_skill_all_learn.h>
#include <protocol/mrpc_gm_monster_spawn.h>
#include <protocol/mrpc_skill_learn.h>
#include <protocol/mrpc_skill_levelup.h>
#include <protocol/mrpc_character_autosave.h>
#include <protocol/mrpc_quest_accept.h>
#include <protocol/mrpc_quest_giveup.h>
#include <protocol/mrpc_quest_complete.h>
#include <protocol/mrpc_indun_reward.h>
#include <protocol/mrpc_item_drop.h>
#include <protocol/mrpc_item_buy.h>
#include <protocol/mrpc_item_decompose.h>
#include <protocol/mrpc_item_destroy.h>
#include <protocol/mrpc_item_enchant_option_make.h>
#include <protocol/mrpc_item_enchant_option_select.h>
#include <protocol/mrpc_item_enchant_option_change.h>
#include <protocol/mrpc_item_equip.h>
#include <protocol/mrpc_item_reinforce.h>
#include <protocol/mrpc_paid_acc_reinforce.h>
#include <protocol/mrpc_item_luck_reinforce.h>
#include <protocol/mrpc_item_make.h>
#include <protocol/mrpc_item_sell.h>
#include <protocol/mrpc_item_use.h>
#include <protocol/mrpc_check_nickname.h>
#include <protocol/mrpc_item_use_change_nickname.h>
#include <protocol/mrpc_character_power.h>
#include <protocol/mrpc_zone_fish.h>
#include <protocol/mrpc_zone_object_collect.h>
#include <protocol/mrpc_zone_treasure_box.h>
#include <protocol/mrpc_zone_item_pickup.h>
#include <protocol/mrpc_inven_expansion.h>
#include <protocol/mrpc_inven_weight_expansion.h>
#include <protocol/mrpc_profesion_make.h>
#include <protocol/mrpc_map_discovery_info.h>
#include <protocol/mrpc_map_discovery_update.h>
#include <protocol/mrpc_exchange_item_withdraw.h>
#include <protocol/mrpc_party_info_update.h>
#include <protocol/mrpc_party_info.h>
#include <protocol/mrpc_pk_setup.h>
#include <protocol/mrpc_mail_send.h>
#include <protocol/mrpc_mail_receive_item.h>
#include <protocol/mrpc_mail_delete.h>
#include <protocol/mrpc_mail_open.h>
#include <protocol/mrpc_gm_getitem.h>
#include <protocol/mrpc_meridians_levelup.h>
#include <protocol/mrpc_acupoints_levelup.h>
#include <protocol/mrpc_party_member_update.h>
#include <protocol/mrpc_buff_insert.h>
#include <protocol/mrpc_buff_delete.h>
#include <protocol/mrpc_guild_change_join_condition.h>
#include <protocol/mrpc_guild_request_member_list.h>
#include <protocol/mrpc_guild_search.h>
#include <protocol/mrpc_repute_quest_finish_count_reset.h>
#include <protocol/mrpc_guild_donation.h>
#include <protocol/mrpc_guild_start_war.h>
#include <protocol/mrpc_guild_try_surrender.h>
#include <protocol/mrpc_guild_respond_surrender.h>
#include <protocol/mrpc_storage_open.h>
#include <protocol/mrpc_account_storage_buy.h>
#include <protocol/mrpc_storage_move.h>
#include <protocol/mrpc_storage_goods_move.h>
#include <protocol/mrpc_storage_expand.h>
#include <protocol/mrpc_indun_auto_matching_reg.h>
#include <protocol/mrpc_indun_auto_matching_complete.h>
#include <protocol/mrpc_indun_play_count.h>
#include <protocol/mrpc_party_vote_request.h>
#include <protocol/mrpc_party_vote_reply.h>
#include <protocol/mrpc_party_vote_result.h>
#include <protocol/mrpc_guild_war_list.h>
#include <protocol/mrpc_gm_guild_war_delete.h>
#include <protocol/mrpc_guild_enemy_list.h>
#include <protocol/mrpc_indun_auto_matching_cancel.h>
#include <protocol/mrpc_item_repair.h>
#include <protocol/mrpc_goods_update.h>
#include <protocol/mrpc_skill_passive_levelup.h>
#include <protocol/mrpc_game_logout.h>
#include <protocol/mrpc_character_zone_enter.h>
#include <protocol/mrpc_guild_alert_start_war.h>
#include <protocol/mrpc_guild_alert_end_war.h>
#include <protocol/mrpc_guild_alert_reject_surrender.h>
#include <protocol/mrpc_guild_alert_surrender.h>
#include <protocol/mrpc_guild_alert_join.h>
#include <protocol/mrpc_guild_alert_join_request.h>
#include <protocol/mrpc_guild_alert_join_request_cancel.h>
#include <protocol/mrpc_guild_alert_join_request_result.h>
#include <protocol/mrpc_guild_alert_leave.h>
#include <protocol/mrpc_guild_alert_ban_for_member.h>
#include <protocol/mrpc_guild_alert_ban.h>
#include <protocol/mrpc_guild_alert_change_grade.h>
#include <protocol/mrpc_guild_alert_change_nickname.h>
#include <protocol/mrpc_guild_alert_change_master.h>
#include <protocol/mrpc_guild_add_exp.h>
#include <protocol/mrpc_guild_alert_add_exp.h>
#include <protocol/mrpc_guild_item_buy.h>
#include <protocol/mrpc_guild_ally_request_accept.h>
#include <protocol/mrpc_guild_ally_request_deny.h>
#include <protocol/mrpc_guild_ally_request_regist.h>
#include <protocol/mrpc_guild_ally_list.h>
#include <protocol/mrpc_guild_ally_request_list.h>
#include <protocol/mrpc_guild_search_by_guid.h>
#include <protocol/mrpc_guild_ally_cancel.h>
#include <protocol/mrpc_guild_ally_alert.h>
#include <protocol/mrpc_guild_ally_detail_info.h>
#include <protocol/mrpc_guild_member_location.h>
#include <protocol/mrpc_guild_member_pk_death_alert.h>
#include <protocol/mrpc_guild_member_list.h>
#include <protocol/mrpc_guild_member_pvp_info.h>
#include <protocol/mrpc_guild_member_daily_reset.h>
#include <protocol/mrpc_guild_member_pvp_update_notify.h>
#include <protocol/mrpc_party_teleport.h>
#include <protocol/mrpc_siege_warfare_all_info.h>
#include <protocol/mrpc_siege_warfare_submit_tender.h>
#include <protocol/mrpc_siege_warfare_alert.h>
#include <protocol/mrpc_siege_warfare_alliance_request.h>
#include <protocol/mrpc_siege_warfare_alliance_cancel.h>
#include <protocol/mrpc_siege_warfare_alliance_response.h>
#include <protocol/mrpc_siege_warfare_alliance_kickout.h>
#include <protocol/mrpc_siege_warfare_alliance_withdrawal.h>
#include <protocol/mrpc_siege_warfare_atk_build_machine.h>
#include <protocol/mrpc_siege_warfare_atk_release_machine.h>
#include <protocol/mrpc_siege_warfare_def_build_machine.h>
#include <protocol/mrpc_siege_warfare_def_release_machine.h>
#include <protocol/mrpc_siege_warfare_battle_result.h>
#include <protocol/mrpc_castle_all_info.h>
#include <protocol/mrpc_castle_set_tax_rate.h>
#include <protocol/mrpc_castle_tax_refund_payment_time.h>
#include <protocol/mrpc_castle_set_tax_distribution.h>
#include <protocol/mrpc_guild_change_notice.h>
#include <protocol/mrpc_guild_alert_change_notice.h>
#include <protocol/mrpc_guild_learn_skill.h>
#include <protocol/mrpc_guild_alert_learn_skill.h>
#include <protocol/mrpc_guild_skill_list.h>
#include <protocol/mrpc_guild_alert_donation.h>
#include <protocol/mrpc_siege_warfare_all_info_for_indun.h>
#include <protocol/mrpc_castle_town_all_info.h>
#include <protocol/mrpc_guild_storage_material_list.h>
#include <protocol/mrpc_guild_item_donation.h>
#include <protocol/mrpc_guild_storage_material_add_cheat.h>
#include <protocol/mrpc_guild_storage_supply_list.h>
#include <protocol/mrpc_guild_storage_supply_insert_item.h>
#include <protocol/mrpc_guild_storage_supply_get_item.h>
#include <protocol/mrpc_chat_world.h>
#include <protocol/mrpc_chat_party.h>
#include <protocol/mrpc_chat_guild.h>
#include <protocol/mrpc_chat_guild_ally.h>
#include <protocol/mrpc_chat_exchange.h>
#include <protocol/mrpc_chat_system.h>
#include <protocol/mrpc_chat_private.h>
#include <protocol/mrpc_guild_storage_share_list.h>
#include <protocol/mrpc_guild_storage_share_insert_item.h>
#include <protocol/mrpc_guild_storage_share_request_get_item.h>
#include <protocol/mrpc_guild_storage_share_master_get_item.h>
#include <protocol/mrpc_guild_storage_share_alert_request_get_item.h>
#include <protocol/mrpc_guild_storage_share_result_get_item.h>
#include <protocol/mrpc_guild_storage_share_extend.h>
#include <protocol/mrpc_guild_storage_share_request_get_item_list.h>
#include <protocol/mrpc_castle_town_return.h>
#include <protocol/mrpc_enchant_stone_slot_open.h>
#include <protocol/mrpc_enchant_stone_equip.h>
#include <protocol/mrpc_enchant_stone_upgrade.h>
#include <protocol/mrpc_enchant_stone_compose.h>
#include <protocol/mrpc_castle_town_work.h>
#include <protocol/mrpc_castle_town_house_fire.h>
#include <protocol/mrpc_gameitem_option_update.h>
#include <protocol/mrpc_dropitem_delete.h>
#include <protocol/mrpc_castle_town_arsenal_build.h>
#include <protocol/mrpc_guild_storage_treasure_list.h>
#include <protocol/mrpc_guild_storage_treasure_get_auction.h>
#include <protocol/mrpc_guild_storage_treasure_confirm_auction.h>
#include <protocol/mrpc_guild_storage_treasure_alert_lost_top_request.h>
#include <protocol/mrpc_guild_storage_treasure_alert_auction_finish.h>
#include <protocol/mrpc_guild_storage_treasure_request.h>
#include <protocol/mrpc_guild_dungeon_prepare_create.h>
#include <protocol/mrpc_guild_dungeon_update.h>
#include <protocol/mrpc_guild_dungeon_clear.h>
#include <protocol/mrpc_guild_dungeon_create.h>
#include <protocol/mrpc_castle_town_arsenal_build_donate.h>
#include <protocol/mrpc_castle_town_arsenal_build_end.h>
#include <protocol/mrpc_castle_town_start_specialties.h>
#include <protocol/mrpc_castle_town_start_specialties_delivery.h>
#include <protocol/mrpc_castle_town_end_specialties_delivery.h>
#include <protocol/mrpc_gm_quest_clear.h>
#include <protocol/mrpc_gm_quest_clear_list.h>
#include <protocol/mrpc_gm_quest_accept.h>
#include <protocol/mrpc_castle_town_owner_update.h>
#include <protocol/mrpc_castle_town_work_end.h>
#include <protocol/mrpc_guild_check_quest_condition.h>
#include <protocol/mrpc_guild_quest_reward.h>
#include <protocol/mrpc_guild_register_master_order_quest.h>
#include <protocol/mrpc_guild_alert_register_master_order_quest.h>
#include <protocol/mrpc_guild_complete_master_order_quest.h>
#include <protocol/mrpc_guild_finish_master_order_quest.h>
#include <protocol/mrpc_guild_alert_finish_master_order_quest.h>
#include <protocol/mrpc_castle_town_start_dinner.h>
#include <protocol/mrpc_castle_town_dinner_get_item.h>
#include <protocol/mrpc_vehicle_add.h>
#include <protocol/mrpc_vehicle_equip.h>
#include <protocol/mrpc_vehicle_food.h>
#include <protocol/mrpc_vehicle_equip_item.h>
#include <protocol/mrpc_vehicle_expire.h>
#include <protocol/mrpc_randombox_open.h>
#include <protocol/mrpc_guild_dungeon_member_damage.h>
#include <protocol/mrpc_castle_dungeon_entrance_fee_change.h>
#include <protocol/mrpc_guild_alert_create_dungeon.h>
#include <protocol/mrpc_siege_warfare_observer_count.h>
#include <protocol/mrpc_pet_equip.h>
#include <protocol/mrpc_pet_feed.h>
#include <protocol/mrpc_pet_mix.h>
#include <protocol/mrpc_castle_dungeon_entrance_fee_apply.h>
#include <protocol/mrpc_siege_bot_create.h>
#include <protocol/mrpc_gm_get_pet.h>
#include <protocol/mrpc_castle_dungeon_entrance_fee_tax_update.h>
#include <protocol/mrpc_pk_record_add.h>
#include <protocol/mrpc_pk_revenge_add.h>
#include <protocol/mrpc_pk_record_revenge.h>
#include <protocol/mrpc_pk_record_delete.h>
#include <protocol/mrpc_pk_revenge_delete.h>
#include <protocol/mrpc_pk_revenge_trace.h>
#include <protocol/mrpc_friend_request.h>
#include <protocol/mrpc_friend_delete.h>
#include <protocol/mrpc_friend_request_response.h>
#include <protocol/mrpc_friend_request_response_all.h>
#include <protocol/mrpc_friend_list.h>
#include <protocol/mrpc_mentor_register.h>
#include <protocol/mrpc_mentor_request.h>
#include <protocol/mrpc_mentor_buff.h>
#include <protocol/mrpc_ranking_save_info.h>
#include <protocol/mrpc_achieve_add.h>
#include <protocol/mrpc_title_add.h>
#include <protocol/mrpc_title_equip.h>
#include <protocol/mrpc_dictionary_add.h>
#include <protocol/mrpc_dictionary_get.h>
#include <protocol/mrpc_ranking_reward_title.h>
#include <protocol/mrpc_wanted_murder_register.h>
#include <protocol/mrpc_wanted_murder_reward.h>
#include <protocol/mrpc_wanted_murder_kill.h>
#include <protocol/mrpc_zone_teleport_save_area.h>
#include <protocol/mrpc_show_costume.h>
#include <protocol/mrpc_wanted_murder_reward_check.h>
#include <protocol/mrpc_guild_change_introduction.h>
#include <protocol/mrpc_guild_pr.h>
#include <protocol/mrpc_guild_invite.h>
#include <protocol/mrpc_guild_invite_accept.h>
#include <protocol/mrpc_guild_invite_refusal.h>
#include <protocol/mrpc_guild_invite_notify.h>
#include <protocol/mrpc_guild_pr_notify.h>
#include <protocol/mrpc_zone_teleport_save_area_delete.h>
#include <protocol/mrpc_dictionary_reward_get.h>
#include <protocol/mrpc_dictionary_achieve_rate_get.h>
#include <protocol/mrpc_tutorial_complete.h>
#include <protocol/mrpc_gm_dictionary_add.h>
#include <protocol/mrpc_start_ai_service.h>
#include <protocol/mrpc_logout_ai_service.h>
#include <protocol/mrpc_dictionary_expire.h>
#include <protocol/mrpc_gm_quest_initialization.h>
#include <protocol/mrpc_item_acc_reinforce.h>
#include <protocol/mrpc_cash_shop_info.h>
#include <protocol/mrpc_cash_shop_cart_get.h>
#include <protocol/mrpc_cash_shop_buy.h>
#include <protocol/mrpc_gm_achieve_all_get.h>
#include <protocol/mrpc_mentor_levelup_reward.h>
#include <protocol/mrpc_ai_setup_config.h>
#include <protocol/mrpc_gm_skill_expup.h>
#include <protocol/mrpc_server_info.h>
#include <protocol/mrpc_cash_shop_exchange_reset.h>
#include <protocol/mrpc_cash_shop_limited_product.h>
#include <protocol/mrpc_guild_shipwar_info.h>
#include <protocol/mrpc_guild_shipwar_request.h>
#include <protocol/mrpc_gm_siege_state.h>
#include <protocol/mrpc_gm_exchange_set_reg_latency.h>
#include <protocol/mrpc_gm_exchange_set_manual_latency.h>
#include <protocol/mrpc_server_use_count.h>
#include <protocol/mrpc_channel_remove.h>
#include <protocol/mrpc_guild_shipwar_create.h>
#include <protocol/mrpc_guild_shipwar_prepare_request.h>
#include <protocol/mrpc_guild_shipwar_calculate.h>
#include <protocol/mrpc_red_dot_noti.h>
#include <protocol/mrpc_private_chatting_disable_update.h>
#include <protocol/mrpc_cash_shop_daily_get.h>
#include <protocol/mrpc_town_rental_request.h>
#include <protocol/mrpc_town_create.h>
#include <protocol/mrpc_town_alert.h>
#include <protocol/mrpc_town_rental_continuation.h>
#include <protocol/mrpc_schedule_info_list.h>
#include <protocol/mrpc_town_indun_create_req.h>
#include <protocol/mrpc_guild_shipwar_match_failed.h>
#include <protocol/mrpc_subscription_add.h>
#include <protocol/mrpc_subscription_info.h>
#include <protocol/mrpc_subscription_del.h>
#include <protocol/mrpc_transform_avatar.h>
#include <protocol/mrpc_mentor_party_buff.h>
#include <protocol/mrpc_dictionary_get_all.h>
#include <protocol/mrpc_channel_create.h>
#include <protocol/mrpc_siege_warfare_victory_character_info.h>
#include <protocol/mrpc_gm_create_bot.h>
#include <protocol/mrpc_npc_intimacy_reward.h>
#include <protocol/mrpc_slot_option_make.h>
#include <protocol/mrpc_slot_option_select.h>
#include <protocol/mrpc_slot_upgrade.h>
#include <protocol/mrpc_change_pet_team.h>
#include <protocol/mrpc_npc_intimacy_reward_get.h>
#include <protocol/mrpc_treasureboxkey_update.h>
#include <protocol/mrpc_guild_treasurebox_reward.h>
#include <protocol/mrpc_wanted_murder_target.h>
#include <protocol/mrpc_wanted_murder_trace.h>
#include <protocol/mrpc_seasonpass_change.h>
#include <protocol/mrpc_seasonpass_unlock.h>
#include <protocol/mrpc_seasonpass_reward.h>
#include <protocol/mrpc_seasonpass_challenge_complet.h>
#include <protocol/mrpc_seasonpass_challenge_update.h>
#include <protocol/mrpc_pk_alert_record_remove.h>
#include <protocol/mrpc_gm_avatar_get.h>
#include <protocol/mrpc_avatar_mix.h>
#include <protocol/mrpc_avatar_slot_set.h>
#include <protocol/mrpc_guild_goods_update.h>
#include <protocol/mrpc_guild_goods_exchange.h>
#include <protocol/mrpc_guild_mark_change.h>
#include <protocol/mrpc_guild_alert_change_mark.h>
#include <protocol/mrpc_ranking_character_delete.h>
#include <protocol/mrpc_guild_gold_alert.h>
#include <protocol/mrpc_castle_owner_change_mark.h>
#include <protocol/mrpc_mail_list_send.h>
#include <protocol/mrpc_event_reward_reset.h>
#include <protocol/mrpc_item_lock.h>
#include <protocol/mrpc_guild_alert_storage_treasure_new.h>
#include <protocol/mrpc_pk_record_viewed.h>
#include <protocol/mrpc_lord_worship.h>
#include <protocol/mrpc_lord_message.h>
#include <protocol/mrpc_lord_bless_buff.h>
#include <protocol/mrpc_revive_list.h>
#include <protocol/mrpc_recovery_exp.h>
#include <protocol/mrpc_get_revive_list.h>
#include <protocol/mrpc_secretvalley_state.h>
#include <protocol/mrpc_illusion_dungeon_update.h>
#include <protocol/mrpc_illusion_dungeon_time_charge.h>
#include <protocol/mrpc_zone_seal_device_use.h>
#include <protocol/mrpc_blackiron_sell_regist.h>
#include <protocol/mrpc_guild_blackiron_alert.h>
#include <protocol/mrpc_blackiron_sell_info.h>
#include <protocol/mrpc_gm_reflection_add.h>
#include <protocol/mrpc_reflection_equip.h>
#include <protocol/mrpc_reflection_mix.h>
#include <protocol/mrpc_customizing_save.h>
#include <protocol/mrpc_blackiron_buy.h>
#include <protocol/mrpc_secretvalley_set_owner.h>
#include <protocol/mrpc_secretvalley_set_owner_info.h>
#include <protocol/mrpc_gm_add_guild_goods.h>
#include <protocol/mrpc_blackiron_collect_tax.h>
#include <protocol/mrpc_temp_reflection_change.h>
#include <protocol/mrpc_temp_reflection_confirm.h>
#include <protocol/mrpc_temp_reflection_get.h>
#include <protocol/mrpc_arena_battle_match_regist.h>
#include <protocol/mrpc_arena_battle_match_regist_cancel.h>
#include <protocol/mrpc_arena_battle_create.h>
#include <protocol/mrpc_gm_arena_battle_start.h>
#include <protocol/mrpc_arena_battle_add_score.h>
#include <protocol/mrpc_arena_battle_season_reward.h>
#include <protocol/mrpc_skill_force_reinforce.h>
#include <protocol/mrpc_mandala_rotation.h>
#include <protocol/mrpc_mandala_node_add.h>
#include <protocol/mrpc_mandala_node_levelup.h>
#include <protocol/mrpc_mandala_reset.h>
#include <protocol/mrpc_mandala_node_equip.h>
#include <protocol/mrpc_mandala_stone_upgrade.h>
#include <protocol/mrpc_auto_matching_state.h>
#include <protocol/mrpc_party_pr.h>
#include <protocol/mrpc_guild_alert_member_contribution_update.h>
#include <protocol/mrpc_gm_profesion_update.h>
#include <protocol/mrpc_secretvalley_info.h>
#include <protocol/mrpc_street_stall_start.h>
#include <protocol/mrpc_street_stall_update.h>
#include <protocol/mrpc_street_stall_reset_time_update.h>
#include <protocol/mrpc_street_stall_end.h>
#include <protocol/mrpc_contents_onoff_update.h>
#include <protocol/mrpc_contents_onoff_list.h>
#include <protocol/mrpc_ranking_reset.h>
#include <protocol/mrpc_ranking_data_update.h>
#include <protocol/mrpc_ranking_update.h>
#include <protocol/mrpc_gm_api_user_kick.h>
#include <protocol/mrpc_gm_get_vehicle.h>
#include <protocol/mrpc_achieve_reward.h>
#include <protocol/mrpc_gm_api_user_kick_cuid.h>
#include <protocol/mrpc_cashshop_payment.h>
#include <protocol/mrpc_gm_skill_force_edit.h>
#include <protocol/mrpc_gm_illusion_dungeon_update.h>
#include <protocol/mrpc_gm_guild_shipwar_league_update.h>
#include <protocol/mrpc_gm_guild_dungeon_reset.h>
#include <protocol/mrpc_gm_guild_shipwar_state.h>
#include <protocol/mrpc_gm_guild_add_exp.h>
#include <protocol/mrpc_gm_guild_storage_treasure_insert_item.h>
#include <protocol/mrpc_gm_guild_ally_delete.h>
#include <protocol/mrpc_gm_arena_calculate_season_ranking.h>
#include <protocol/mrpc_send_nickname_disable.h>
#include <protocol/mrpc_quest_reward_change.h>
#include <protocol/mrpc_arena_battle_matching_count.h>
#include <protocol/mrpc_party_invite_cancel.h>
#include <protocol/mrpc_cheatkey_drop_probalility.h>
#include <protocol/mrpc_cheatkey_mix_probalility.h>
#include <protocol/mrpc_blackiron_calc_tax.h>
#include <protocol/mrpc_character_guild_join_time_reset.h>
#include <protocol/mrpc_gm_api_kick_all.h>
#include <protocol/mrpc_arena_battle_result.h>
#include <protocol/mrpc_temp_pet_get.h>
#include <protocol/mrpc_temp_pet_change.h>
#include <protocol/mrpc_temp_pet_confirm.h>
#include <protocol/mrpc_fieldboss_spawn_regist.h>
#include <protocol/mrpc_field_boss_spawn.h>
#include <protocol/mrpc_shipwar_character_result.h>
#include <protocol/mrpc_mandala_node_reset.h>
#include <protocol/mrpc_street_stall_pr.h>
#include <protocol/mrpc_update_speed_hack_check.h>
#include <protocol/mrpc_update_not_allow_packet.h>
#include <protocol/mrpc_gm_mandala_node_add.h>
#include <protocol/mrpc_mentor_teleport_check.h>
#include <protocol/mrpc_npc_shop_open.h>
#include <protocol/mrpc_guild_alert_dungeon_info.h>
#include <protocol/mrpc_guild_dungeon_enter_charge.h>
#include <protocol/mrpc_cash_shop_item_list.h>
#include <protocol/mrpc_cash_limit_product_noti.h>
#include <protocol/mrpc_cheatkey_stoneslotopen_probalility.h>
#include <protocol/mrpc_cheatkey_stonecompose_probalility.h>
#include <protocol/mrpc_occupationwar_tender_deposit.h>
#include <protocol/mrpc_occupationwar_tender_withdraw.h>
#include <protocol/mrpc_occupationwar_war_server_decide.h>
#include <protocol/mrpc_global_occupationwar_war_server_decide.h>
#include <protocol/mrpc_darksteel_storage_darksteel_pay.h>
#include <protocol/mrpc_guild_shipwar_season_reward.h>
#include <protocol/mrpc_guild_shipwar_unearned_win_alarm.h>
#include <protocol/mrpc_occupationwar_challenge_request.h>
#include <protocol/mrpc_occupationwar_challenge_request_info.h>
#include <protocol/mrpc_occupationwar_info.h>
#include <protocol/mrpc_occupationwar_tender_total_info.h>
#include <protocol/mrpc_occupationwar_guild_info.h>
// #include <protocol/mrpc_gm_occupationwar_initialize.h>
// #include <protocol/mrpc_gm_occupationwar_set_schedule.h>
// #include <protocol/mrpc_gm_occupationwar_schedule_reset.h>
// #include <protocol/mrpc_gm_darksteel_storage_reload.h>
// #include <protocol/mrpc_gm_darksteel_storage_owner_update.h>
// #include <protocol/mrpc_gm_darksteel_storage_owner_info.h>
// #include <protocol/mrpc_gm_occupationwar_all_info_update_request.h>
#include <protocol/mrpc_guild_search_custom.h>
#include <protocol/mrpc_friend_target_delete.h>
#include <protocol/mrpc_update_use_not_allow_duplication_login.h>
#include <protocol/mrpc_player_duplication_login_info.h>
#include <protocol/mrpc_wallet_login.h>
#include <protocol/mrpc_wallet_linked_account.h>
#include <protocol/mrpc_get_contract_address.h>
#include <protocol/mrpc_trade_darksteelbox_to_token.h>
#include <protocol/mrpc_trade_token_to_darksteelbox.h>
#include <protocol/mrpc_approve_make_transaction.h>
#include <protocol/mrpc_approve_send_transaction.h>
#include <protocol/mrpc_global_exchange_pre_register.h>
#include <protocol/mrpc_global_exchange_register.h>
#include <protocol/mrpc_global_exchange_register_complete.h>
#include <protocol/mrpc_global_exchange_register_cancel.h>
#include <protocol/mrpc_global_exchange_buy.h>
#include <protocol/mrpc_global_exchange_gold_withdraw.h>
#include <protocol/mrpc_global_exchange_item_withdraw.h>
#include <protocol/mrpc_global_exchange_item_get_insert.h>
#include <protocol/mrpc_staking_make_tx.h>
#include <protocol/mrpc_staking_send_tx.h>
#include <protocol/mrpc_claim_make_tx.h>
#include <protocol/mrpc_claim_send_tx.h>
#include <protocol/mrpc_boss_governance_server_decide_process.h>
#include <protocol/mrpc_boss_governance_get_treasurebox_dbinfo.h>
#include <protocol/mrpc_governance_staking.h>
#include <protocol/mrpc_governance_unstaking.h>
#include <protocol/mrpc_token_history_item_get.h>
#include <protocol/mrpc_token_history_item_select.h>
#include <protocol/mrpc_server_connected_info.h>
#include <protocol/mrpc_server_contract_agenda_info.h>
#include <protocol/mrpc_update_debug_print_rpcinfo.h>
#include <protocol/mrpc_heartbeat_check.h>
#include <protocol/mrpc_game_duplicate_login.h>
#include <protocol/mrpc_global_party_governance_staking.h>
#include <protocol/mrpc_global_party_governance_unstaking.h>
#include <protocol/mrpc_global_party_governance_decide_info.h>
#include <protocol/mrpc_global_party_governance_rank.h>
#include <protocol/mrpc_gm_global_governance_decide.h>
#include <protocol/mrpc_gm_character_last_time_change.h>
#include <protocol/mrpc_occupationwar_owner_guild_remove.h>
#include <protocol/mrpc_occupationwar_gameserver_log.h>
#include <protocol/mrpc_global_party_governance_account_staking.h>
#include <protocol/mrpc_advertisement_exp_restore.h>
#include <protocol/mrpc_recovery_exp_ad.h>
#include <protocol/mrpc_advertisement_reward.h>
#include <protocol/mrpc_reward_ad.h>
#include <protocol/mrpc_advertisement_event_reward.h>
#include <protocol/mrpc_global_party_governance_token_history.h>
#include <protocol/mrpc_indun_party_finish_notify.h>
#include <protocol/mrpc_change_character_zone_info.h>
#include <protocol/mrpc_party_leave_by_invite_accept.h>
#include <protocol/mrpc_server_relocation_lock.h>
#include <protocol/mrpc_server_relocation_process_global_log.h>
#include <protocol/mrpc_gm_api_character_subscription_update.h>
#include <protocol/mrpc_dimension_dungeon_contribution.h>
#include <protocol/mrpc_dimension_dungeon_contribution_daily_reset.h>
#include <protocol/mrpc_dimension_dungeon_state.h>
#include <protocol/mrpc_dimension_dungeon_contribution_item_history.h>
#include <protocol/mrpc_dimension_dungeon_enter_check.h>
#include <protocol/mrpc_party_member_enter_status.h>
#include <protocol/mrpc_party_member_enter_status_relay.h>
#include <protocol/mrpc_dimension_dungeon_contribution_buff.h>
#include <protocol/mrpc_gm_dimension_dungeon_cmd.h>
#include <protocol/mrpc_gm_dimension_dungeon_crack_cmd.h>
#include <protocol/mrpc_blood_dedicate_reward_change.h>
#include <protocol/mrpc_blood_dedicate_worldboss_summon.h>
#include <protocol/mrpc_blood_dedicate_status.h>
#include <protocol/mrpc_blood_dedicate_worldboss_init.h>
#include <protocol/mrpc_gm_blood_dedicate_worldboss.h>
#include <protocol/mrpc_blood_dedicate_worldboss_summon_state.h>
#include <protocol/mrpc_blood_dedicate_worldboss_notify.h>
#include <protocol/mrpc_refresh_character_ranking_info.h>
#include <protocol/mrpc_reinitialize_ranking_info.h>
#include <protocol/mrpc_check_ranking_season_reward.h>
#include <protocol/mrpc_expert_equipment_create.h>
#include <protocol/mrpc_expert_equipment_enchant_stone_equip.h>
#include <protocol/mrpc_expert_equipment_get_info.h>
#include <protocol/mrpc_expert_equipment_equip.h>
#include <protocol/mrpc_expert_equipment_reinforce.h>
#include <protocol/mrpc_expert_equipment_reinforce_cheat.h>
#include <protocol/mrpc_expert_equipment_enchant_stone_upgrade.h>
#include <protocol/mrpc_expert_run.h>
#include <protocol/mrpc_season_mandala_info_get.h>
#include <protocol/mrpc_season_mandala_info_update.h>

#include <protocol/mrpc_equipment_awaken.h>
#include <protocol/mrpc_equipment_awaken_option_confirmed.h>

#include <protocol/mrpc_gate_castle_dungeon_info.h>
#include <protocol/mrpc_gate_castle_view_owner_info.h>
#include <protocol/mrpc_gate_castle_tax_with_member_info.h>
#include <protocol/mrpc_gate_castle_town_info_by_guild_guid.h>
#include <protocol/mrpc_gate_castle_town_managing_info.h>
#include <protocol/mrpc_gate_castle_town_single_managing_info.h>
#include <protocol/mrpc_gate_castle_town_save_bag_info.h>
#include <protocol/mrpc_gate_castle_town_log.h>
#include <protocol/mrpc_gate_character_info_view.h>
#include <protocol/mrpc_gate_token_history_info_get.h>
#include <protocol/mrpc_gate_community_server_getinfo.h>
#include <protocol/mrpc_gate_contract_get_nonce.h>
#include <protocol/mrpc_gate_contract_get_address.h>
#include <protocol/mrpc_gate_contract_get_balance.h>
#include <protocol/mrpc_gate_contract_token_allowance.h>
#include <protocol/mrpc_gate_contract_get_limit.h>
#include <protocol/mrpc_gate_contract_get_staking_info.h>
#include <protocol/mrpc_gate_contract_get_balance_to_wdoller.h>
#include <protocol/mrpc_gate_world_boss_statking_player_info.h>
#include <protocol/mrpc_gate_coupon_use.h>
#include <protocol/mrpc_gate_friend_list.h>
#include <protocol/mrpc_gate_mentor_position.h>
#include <protocol/mrpc_gate_friend_request_count.h>
#include <protocol/mrpc_gate_friend_requested_list.h>
#include <protocol/mrpc_gate_game_option_save.h>
#include <protocol/mrpc_gate_game_option_select.h>
#include <protocol/mrpc_gate_game_setup_hash_select.h>
#include <protocol/mrpc_gate_game_setup_save.h>
#include <protocol/mrpc_gate_game_setup_select.h>
#include <protocol/mrpc_gate_guild_dungeon_member_damage.h>
#include <protocol/mrpc_gate_guild_dungeon_goods.h>
#include <protocol/mrpc_gate_guild_skill_goods.h>
#include <protocol/mrpc_gate_guild_share_storage_log.h>
#include <protocol/mrpc_gate_secretvalley_owner_info.h>
#include <protocol/mrpc_gate_guild_league_rank.h>
#include <protocol/mrpc_gate_guild_storage_history.h>
#include <protocol/mrpc_gate_mail_check.h>
#include <protocol/mrpc_gate_mail_list.h>
#include <protocol/mrpc_gate_mentor_info.h>
#include <protocol/mrpc_gate_mentor_list.h>
#include <protocol/mrpc_gate_mentor_rev_req_list.h>
#include <protocol/mrpc_gate_occupationwar_tender_history.h>
#include <protocol/mrpc_gate_darksteel_storage_info.h>
#include <protocol/mrpc_gate_darksteel_storage_history.h>
#include <protocol/mrpc_gate_darksteel_storage_darksteel_daily_pay.h>
#include <protocol/mrpc_gate_occupationwar_challenge_request_list.h>
#include <protocol/mrpc_gate_ranking_info.h>
#include <protocol/mrpc_gate_ranking_info_new.h>
#include <protocol/mrpc_gate_refinery_exchange_limit_check.h>
#include <protocol/mrpc_gate_search_around_party.h>
#include <protocol/mrpc_gate_search_category_party.h>
#include <protocol/mrpc_gate_search_user.h>
#include <protocol/mrpc_gate_shipwar_result_list.h>
#include <protocol/mrpc_gate_shipwar_result.h>
#include <protocol/mrpc_gate_siege_warfare_alliance_list.h>
#include <protocol/mrpc_gate_siege_warfare_alliance_receive_list.h>
#include <protocol/mrpc_gate_siege_warfare_atk_machine_info.h>
#include <protocol/mrpc_gate_siege_warfare_guild_search.h>
#include <protocol/mrpc_gate_siegewarfare_observer_count.h>
#include <protocol/mrpc_gate_siege_warfare_tender_info.h>
#include <protocol/mrpc_gate_street_stall_sell_info.h>
#include <protocol/mrpc_gate_wanted_murder_list.h>
#include <protocol/mrpc_gate_wanted_murder_register_list.h>
#include <protocol/mrpc_gate_wanted_murder_reward_list.h>
#include <protocol/mrpc_gate_exchange_buybag_info.h>
#include <protocol/mrpc_gate_exchange_history.h>
#include <protocol/mrpc_gate_exchange_itemcount_all.h>
#include <protocol/mrpc_gate_exchange_itemcount_type.h>
#include <protocol/mrpc_gate_exchange_item_detail.h>
#include <protocol/mrpc_gate_exchange_itemid_reg_count_lists.h>
#include <protocol/mrpc_gate_exchange_itemid_lists.h>
#include <protocol/mrpc_gate_exchange_itemid_reinforce_count.h>
#include <protocol/mrpc_gate_exchange_itemid_reinforce_list.h>
#include <protocol/mrpc_gate_exchange_itemtype_count.h>
#include <protocol/mrpc_gate_exchange_marketprice.h>
#include <protocol/mrpc_gate_exchange_registrant_info.h>
#include <protocol/mrpc_gate_field_boss_regist_info.h>
#include <protocol/mrpc_gate_event_info.h>
#include <protocol/mrpc_gate_event_reward.h>
#include <protocol/mrpc_gate_global_exchange_buybag_info.h>
#include <protocol/mrpc_gate_global_exchange_history.h>
#include <protocol/mrpc_gate_global_exchange_itemcount_all.h>
#include <protocol/mrpc_gate_global_exchange_itemcount_type.h>
#include <protocol/mrpc_gate_global_exchange_item_detail.h>
#include <protocol/mrpc_gate_global_exchange_itemid_reg_count_lists.h>
#include <protocol/mrpc_gate_global_exchange_itemid_lists.h>
#include <protocol/mrpc_gate_global_exchange_itemid_reinforce_count.h>
#include <protocol/mrpc_gate_global_exchange_itemid_reinforce_list.h>
#include <protocol/mrpc_gate_global_exchange_itemtype_count.h>
#include <protocol/mrpc_gate_global_exchange_marketprice.h>
#include <protocol/mrpc_gate_global_exchange_registrant_info.h>
#include <protocol/mrpc_gate_cash_shop_info.h>
#include <protocol/mrpc_gate_contents_onoff_list.h>
#include <protocol/mrpc_gate_pay_start.h>
#include <protocol/mrpc_gate_pay_verify.h>
#include <protocol/mrpc_gate_pre_verify.h>
#include <protocol/mrpc_gate_promo_verify.h>
#include <protocol/mrpc_gate_cash_shop_item_list.h>
#include <protocol/mrpc_gate_lobby_character_create.h>
#include <protocol/mrpc_gate_lobby_character_delete.h>
#include <protocol/mrpc_gate_lobby_character_delete_cancel.h>
#include <protocol/mrpc_gate_lobby_character_select.h>
#include <protocol/mrpc_gate_lobby_gameplaylogin.h>
#include <protocol/mrpc_gate_lobby_gamelogin_await_cancel.h>
#include <protocol/mrpc_gate_get_available_font_list.h>
#include <protocol/mrpc_gate_channel_status.h>
#include <protocol/mrpc_gate_channel_full_check.h>
#include <protocol/mrpc_gate_loginserver_lobby_login.h>
#include <protocol/mrpc_gate_loginserver_duplicate_login.h>
#include <protocol/mrpc_gate_arena_battle_ranking.h>
#include <protocol/mrpc_gate_arena_battle_info.h>
#include <protocol/mrpc_gate_arena_battle_result_list.h>
#include <protocol/mrpc_gate_arena_battle_result.h>
#include <protocol/mrpc_gate_guildshipwar_season_reward.h>
#include <protocol/mrpc_gate_world_boss_statking_board_info.h>
#include <protocol/mrpc_gate_occupationwar_statking_board_info.h>
#include <protocol/mrpc_gate_occupationwar_schedule_info.h>
#include <protocol/mrpc_gate_world_boss_linked_wallet_info.h>
#include <protocol/mrpc_gate_worldboard_guild_league_rank.h>
#include <protocol/mrpc_gate_worldboard_shipwar_result_list.h>
#include <protocol/mrpc_gate_worldboard_shipwar_result.h>
#include <protocol/mrpc_gate_get_all_balance_swap_token.h>
#include <protocol/mrpc_gate_wemix_pay_start.h>
#include <protocol/mrpc_gate_wemix_pay_end.h>
#include <protocol/mrpc_gate_dogma_pay_start.h>
#include <protocol/mrpc_gate_dogma_pay_end.h>
#include <protocol/mrpc_gate_dogma_get_oracle.h>
#include <protocol/mrpc_gate_get_wemix_amount.h>
#include <protocol/mrpc_gate_get_wemix_history.h>
#include <protocol/mrpc_gate_advertisement_info.h>
#include <protocol/mrpc_gate_advertisement_exp_restore.h>
#include <protocol/mrpc_gate_advertisement_reward.h>
#include <protocol/mrpc_gate_advertisement_event_reward.h>
#include <protocol/mrpc_gate_client_session_open.h>
#include <protocol/mrpc_gate_client_session_closed.h>
#include <protocol/mrpc_gate_rpc_chatting.h>
#include <protocol/mrpc_gate_community_login.h>
#include <protocol/mrpc_gate_chatting.h>
#include <protocol/mrpc_gate_chatting_block.h>
#include <protocol/mrpc_gate_chatting_block_list.h>
#include <protocol/mrpc_gate_private_chatting_state.h>
#include <protocol/mrpc_gate_server_relocation_list.h>
#include <protocol/mrpc_gate_dimension_dungeon_schedule.h>
#include <protocol/mrpc_gate_lobby_player_character_select.h>
#include <protocol/mrpc_gate_lobby_player_character_delete.h>
#include <protocol/mrpc_gate_lobby_character_socket_reconnect.h>
#include <protocol/mrpc_gate_blood_dedicate_worldboss_status.h>
#include <protocol/mrpc_server_relocation_recovery_item.h>
#include <protocol/mrpc_server_relocation_data_remove.h>
#include <protocol/mrpc_boss_dungeon_clear.h>
#include <protocol/mrpc_gate_dungeon_ranking_info.h>
#include <protocol/mrpc_boss_dungeon_ranking_refresh.h>
#include <protocol/mrpc_restore_item_list.h>
#include <protocol/mrpc_restore_compose_list.h>
#include <protocol/mrpc_restore_item.h>
#include <protocol/mrpc_restore_compose.h>
#include <protocol/mrpc_season_mandala_reward_update.h>
#include <protocol/mrpc_season_mandala_reward_delete.h>
#include <protocol/mrpc_world_ranking_refresh.h>
#include <protocol/mrpc_season_mandala_reward_delete_all.h>
#include <protocol/mrpc_season_mandala_reward_item_update.h>

#pragma endregion mrpc

#pragma region mrpcs

#include <protocol/struct/mrpcs_login_character.h>
#include <protocol/struct/mrpcs_player_equipitem.h>
#include <protocol/struct/mrpcs_rpc_item.h>
#include <protocol/struct/mrpcs_rpc_item_list.h>
#include <protocol/struct/mrpcs_rpc_redis_login_character.h>
#include <protocol/struct/mrpcs_redis_czone.h>
#include <protocol/struct/mrpcs_redis_channel_zone_list.h>
#include <protocol/struct/mrpcs_redis_lobbyinfo.h>
#include <protocol/struct/mrpcs_redis_rpcinfo.h>
#include <protocol/struct/mrpcs_redis_rpcinfo_list.h>
#include <protocol/struct/mrpcs_redis_serverinfo.h>
#include <protocol/struct/mrpcs_deamontool_server_info.h>
#include <protocol/struct/mrpcs_server_group_info.h>
#include <protocol/struct/mrpcs_server_world_info.h>
#include <protocol/struct/mrpcs_server_world_info_list.h>
#include <protocol/struct/mrpcs_server_maintenance_info.h>
#include <protocol/struct/mrpcs_server_maintenance_store_info.h>
#include <protocol/struct/mrpcs_redis_contents_onoff_info.h>
#include <protocol/struct/mrpcs_redis_server_group_state.h>
#include <protocol/struct/mrpcs_exchange.h>
#include <protocol/struct/mrpcs_global_exchange.h>
#include <protocol/struct/mrpcs_exchange_context.h>
#include <protocol/struct/mrpcs_dual_long.h>
#include <protocol/struct/mrpcs_global_exchange_context.h>
#include <protocol/struct/mrpcs_exchange_buybag_item_ex.h>
#include <protocol/struct/mrpcs_exchange_buybag.h>
#include <protocol/struct/mrpcs_global_exchange_purchase_item.h>
#include <protocol/struct/mrpcs_global_exchange_purchase_itembag.h>
#include <protocol/struct/mrpcs_exchange_price.h>
#include <protocol/struct/mrpcs_global_exchange_price.h>
#include <protocol/struct/mrpcs_exchange_realtimeprice.h>
#include <protocol/struct/mrpcs_global_exchange_realtimeprice.h>
#include <protocol/struct/mrpcs_exchange_marketprice.h>
#include <protocol/struct/mrpcs_global_exchange_marketprice.h>
#include <protocol/struct/mrpcs_quest_finish.h>
#include <protocol/struct/mrpcs_indun_character.h>
#include <protocol/struct/mrpcs_indun_character_list.h>
#include <protocol/struct/mrpcs_comm_character.h>
#include <protocol/struct/mrpcs_guild_context.h>
#include <protocol/struct/mrpcs_game_event.h>
#include <protocol/struct/mrpcs_meridians.h>
#include <protocol/struct/mrpcs_siege_warfare_info_for_indun.h>
#include <protocol/struct/mrpcs_castle_town_all_info.h>
#include <protocol/struct/mrpcs_castle_town_info.h>
#include <protocol/struct/mrpcs_item_stone_pair.h>
#include <protocol/struct/mrpcs_enchant_stone_info.h>
#include <protocol/struct/mrpcs_enchant_stone_update_pos.h>
#include <protocol/struct/mrpcs_enchant_stone_update.h>
#include <protocol/struct/mrpcs_enchant_stone_db_item.h>
#include <protocol/struct/mrpcs_gameitem_option_update.h>
#include <protocol/struct/mrpcs_castle_town_specialties_work.h>
#include <protocol/struct/mrpcs_vehicle_autosave.h>
#include <protocol/struct/mrpcs_guild_dungeon_reward.h>
#include <protocol/struct/mrpcs_pk_record_info.h>
#include <protocol/struct/mrpcs_ranking_data.h>
#include <protocol/struct/mrpcs_character_ranking_info.h>
#include <protocol/struct/mrpcs_guild_ranking_info.h>
#include <protocol/struct/mrpcs_profesion_ranking_info.h>
#include <protocol/struct/mrpcs_list_profesion_ranking.h>
#include <protocol/struct/mrpcs_character_autosave.h>
#include <protocol/struct/mrpcs_mentor_request.h>
#include <protocol/struct/mrpcs_list_mentor_request.h>
#include <protocol/struct/mrpcs_list_title.h>
#include <protocol/struct/mrpcs_character_dictionary_stat.h>
#include <protocol/struct/mrpcs_adult_certification.h>
#include <protocol/struct/mrpcs_mail.h>
#include <protocol/struct/mrpcs_server_info.h>
#include <protocol/struct/mrpcs_server_info_list.h>
#include <protocol/struct/mrpcs_server_max_play_user.h>
#include <protocol/struct/mrpcs_guild_shipwar_info.h>
#include <protocol/struct/mrpcs_guild_shipwar_matchup.h>
#include <protocol/struct/mrpcs_teleport_area.h>
#include <protocol/struct/mrpcs_list_seasonpass_challenge.h>
#include <protocol/struct/mrpcs_castle_tax_value.h>
#include <protocol/struct/mrpcs_simple_mail.h>
#include <protocol/struct/mrpcs_simple_mail_box.h>
#include <protocol/struct/mrpcs_avatar_info.h>
#include <protocol/struct/mrpcs_character.h>
#include <protocol/struct/mrpcs_white_list_account.h>
#include <protocol/struct/mrpcs_white_list_address.h>
#include <protocol/struct/mrpcs_reserved_mail.h>
#include <protocol/struct/mrpcs_reserved_mail_list.h>
#include <protocol/struct/mrpcs_comm_object.h>
#include <protocol/struct/mrpcs_comm_message.h>
#include <protocol/struct/mrpcs_comm_message_data.h>
#include <protocol/struct/mrpcs_kick_user_info.h>
#include <protocol/struct/mrpcs_sanctions_account_list.h>
#include <protocol/struct/mrpcs_sanctions_account.h>
#include <protocol/struct/mrpcs_street_stall_sell_info.h>
#include <protocol/struct/mrpcs_server_inspection.h>
#include <protocol/struct/mrpcs_server_inspection_list.h>
#include <protocol/struct/mrpcs_coupon_publish.h>
#include <protocol/struct/mrpcs_coupon_publish_list.h>
#include <protocol/struct/mrpcs_fixed_coupon_use.h>
#include <protocol/struct/mrpcs_random_coupon.h>
#include <protocol/struct/mrpcs_random_coupon_use.h>
#include <protocol/struct/mrpcs_fixed_coupon_use_list.h>
#include <protocol/struct/mrpcs_random_coupon_use_list.h>
#include <protocol/struct/mrpcs_coupon_code.h>
#include <protocol/struct/mrpcs_coupon_code_list.h>
#include <protocol/struct/mrpcs_white_list_use.h>
#include <protocol/struct/mrpcs_white_list_info.h>
#include <protocol/struct/mrpcs_achieve_list.h>
#include <protocol/struct/mrpcs_await_info.h>
#include <protocol/struct/mrpcs_channel_ccu_info.h>
#include <protocol/struct/mrpcs_server_channel_ccu_info.h>
#include <protocol/struct/mrpcs_drop_probalility_info.h>
#include <protocol/struct/mrpcs_drop_probalility_info_list.h>
#include <protocol/struct/mrpcs_cash_cart_count.h>
#include <protocol/struct/mrpcs_shipwar_character_result.h>
#include <protocol/struct/mrpcs_not_allow_packet.h>
#include <protocol/struct/mrpcs_not_allow_packet_list.h>
#include <protocol/struct/mrpcs_world_arena_team.h>
#include <protocol/struct/mrpcs_stoneslotopen_probalility.h>
#include <protocol/struct/mrpcs_stoneslotopen_probalility_info.h>
#include <protocol/struct/mrpcs_contents_onoff.h>
#include <protocol/struct/mrpcs_contents_onoff_info.h>
#include <protocol/struct/mrpcs_character_enable.h>
#include <protocol/struct/mrpcs_account_uncheater.h>
#include <protocol/struct/mrpcs_darksteel_storage_create.h>
#include <protocol/struct/mrpcs_darksteel_storage_darksteel_pay_to_mail.h>
#include <protocol/struct/mrpcs_darksteel_storage_daily_pay_info.h>
#include <protocol/struct/mrpcs_darksteel_storage_history.h>
#include <protocol/struct/mrpcs_occupationwar_base_info.h>
#include <protocol/struct/mrpcs_darksteel_storage_pay_tax_type.h>
#include <protocol/struct/mrpcs_occupationwar_owner_info.h>
#include <protocol/struct/mrpcs_occupationwar_war_map_info.h>
#include <protocol/struct/mrpcs_occupationwar_server_info.h>
#include <protocol/struct/mrpcs_darksteel_box_keep_server_info.h>
#include <protocol/struct/mrpcs_occupationwar_darksteel_tax_log.h>
#include <protocol/struct/mrpcs_occupationwar_darksteel_tax_log_info.h>
#include <protocol/struct/mrpcs_occupationwar_darksteel_tax_log_info_list.h>
#include <protocol/struct/mrpcs_occupationwar_owner_disqualify.h>
#include <protocol/struct/mrpcs_darksteel_pay_tax_info.h>
#include <protocol/struct/mrpcs_boss_governance_summon_onoff_dbdata.h>
#include <protocol/struct/mrpcs_player_login_info.h>
#include <protocol/struct/mrpcs_refinery_daily_limit.h>
#include <protocol/struct/mrpcs_config_address.h>
#include <protocol/struct/mrpcs_config_redis.h>
#include <protocol/struct/mrpcs_config_database.h>
#include <protocol/struct/mrpcs_config_world_data.h>
#include <protocol/struct/mrpcs_boss_governance_treasurebox.h>
#include <protocol/struct/mrpcs_boss_governance_summon_info.h>
#include <protocol/struct/mrpcs_coin_recall_cooltime_info.h>
#include <protocol/struct/mrpcs_boss_governance_info.h>
#include <protocol/struct/mrpcs_contract_agenda.h>
#include <protocol/struct/mrpcs_contract_sector.h>
#include <protocol/struct/mrpcs_contract_agenda_info.h>
#include <protocol/struct/mrpcs_contract_governance_info.h>
#include <protocol/struct/mrpcs_global_exchagne_withdraw_gold_type.h>
#include <protocol/struct/mrpcs_boss_governance_server_info_total.h>
#include <protocol/struct/mrpcs_boss_governance_server_decide_process.h>
#include <protocol/struct/mrpcs_redis_rpc_info.h>
#include <protocol/struct/mrpcs_redis_server_info.h>
#include <protocol/struct/mrpcs_global_ccu_info.h>
#include <protocol/struct/mrpcs_server_channel_ccu_list_channel.h>
#include <protocol/struct/mrpcs_server_channel_ccu_list_user_count.h>
#include <protocol/struct/mrpcs_managed_rpc.h>
#include <protocol/struct/mrpcs_managed_rpc_info.h>
#include <protocol/struct/mrpcs_server_managed_rpc_info.h>
#include <protocol/struct/mrpcs_occupationwar_server_info_total.h>
#include <protocol/struct/mrpcs_global_governance_context.h>
#include <protocol/struct/mrpcs_login_account.h>
#include <protocol/struct/mrpcs_lobby_character.h>
#include <protocol/struct/mrpcs_account_ticket_item.h>
#include <protocol/struct/mrpcs_character_data.h>
#include <protocol/struct/mrpcs_exchange_item_minprice.h>
#include <protocol/struct/mrpcs_occupationwar_schedule_noti.h>
#include <protocol/struct/mrpcs_occupationwar_game_info.h>
#include <protocol/struct/mrpcs_wemix_shop_buy_count.h>
#include <protocol/struct/mrpcs_global_party_governance_info.h>
#include <protocol/struct/mrpcs_subscription_info.h>
#include <protocol/struct/mrpcs_gm_subscription_info.h>
#include <protocol/struct/mrpcs_build_tool_server_info.h>
#include <protocol/struct/mrpcs_build_tool_dev_server.h>
#include <protocol/struct/mrpcs_build_tool_branch.h>
#include <protocol/struct/mrpcs_build_tool_dev_server_state.h>
#include <protocol/struct/mrpcs_build_tool_dev_server_group_state.h>
#include <protocol/struct/mrpcs_api_server_relocation_info.h>
#include <protocol/struct/mrpcs_dimension_dungeon_contribution.h>
#include <protocol/struct/mrpcs_dimension_dungeon_contribution_item.h>
#include <protocol/struct/mrpcs_dimension_dungeon_contribution_status.h>
#include <protocol/struct/mrpcs_summon_object_wave_info.h>
#include <protocol/struct/mrpcs_summon_object_info.h>
#include <protocol/struct/mrpcs_dimension_dungeon_contribution_item_round.h>
#include <protocol/struct/mrpcs_gate_character_reconnect_info.h>
#include <protocol/struct/mrpcs_character_ranking_request_info.h>

#pragma endregion mrpcs



