#pragma once

#include <protocol/base_protocol.h>
#include <protocol/base_protocol_enumstring.h>
#include <protocol/rpc_protocol.h>


#pragma region mp

#include <protocol/mp_error_message.h>
#include <protocol/mp_redirect_notify.h>
#include <protocol/mp_redirect_request.h>
#include <protocol/mp_game_login.h>
#include <protocol/mp_zone_enter.h>
#include <protocol/mp_zone_enter_ready.h>
#include <protocol/mp_zone_leave.h>
#include <protocol/mp_zone_move.h>
#include <protocol/mp_zone_tile_check.h>
#include <protocol/mp_zone_object_move.h>
#include <protocol/mp_skill_start.h>
#include <protocol/mp_skill_damage_result.h>
#include <protocol/mp_special_move_start.h>
#include <protocol/mp_zone_object_update_stat.h>
#include <protocol/mp_zone_delete_buff_debuff.h>
#include <protocol/mp_inven_expansion.h>
#include <protocol/mp_goods_update.h>
#include <protocol/mp_item_buy.h>
#include <protocol/mp_item_equip.h>
#include <protocol/mp_zone_character_item_equip.h>
#include <protocol/mp_item_sell.h>
#include <protocol/mp_item_use.h>
#include <protocol/mp_item_use_change_nickname.h>
#include <protocol/mp_check_nickname.h>
#include <protocol/mp_item_reinforce.h>
#include <protocol/mp_paid_acc_reinforce.h>
#include <protocol/mp_item_luck_reinforce.h>
#include <protocol/mp_item_make.h>
#include <protocol/mp_item_destroy.h>
#include <protocol/mp_item_enchant_option_change.h>
#include <protocol/mp_item_decompose.h>
#include <protocol/mp_character_power.h>
#include <protocol/mp_quest_complete.h>
#include <protocol/mp_quest_giveup.h>
#include <protocol/mp_profesion_make.h>
#include <protocol/mp_map_discovery_update.h>
#include <protocol/mp_map_discovery_info.h>
#include <protocol/mp_gameitem_update.h>
#include <protocol/mp_character_behavior.h>
#include <protocol/mp_indun_enter.h>
#include <protocol/mp_indun_enter_complete.h>
#include <protocol/mp_test_game_login.h>
#include <protocol/mp_gm_spawn_monster.h>
#include <protocol/mp_gm_spawn_treasurebox.h>
#include <protocol/mp_gm_add_exp.h>
#include <protocol/mp_gm_add_expert_exp.h>
#include <protocol/mp_gm_invincibility.h>
#include <protocol/mp_gm_skillopen.h>
#include <protocol/mp_gm_fsminfo.h>
#include <protocol/mp_gm_object_skill_start.h>
#include <protocol/mp_gm_siege_object_spawn.h>
#include <protocol/mp_gm_siege_warfare_change_state.h>
#include <protocol/mp_zone_change_enter.h>
#include <protocol/mp_zone_teleport.h>
#include <protocol/mp_zone_object_loding.h>
#include <protocol/mp_zone_player_info.h>
#include <protocol/mp_zone_monster_info.h>
#include <protocol/mp_zone_character_minion_info.h>
#include <protocol/mp_zone_object_dead.h>
#include <protocol/mp_zone_revive.h>
#include <protocol/mp_zone_character_drop.h>
#include <protocol/mp_character_pk_color.h>
#include <protocol/mp_zone_drop_item_info.h>
#include <protocol/mp_zone_npc_info.h>
#include <protocol/mp_zone_collect_info.h>
#include <protocol/mp_zone_gold_treasure_box_info.h>
#include <protocol/mp_zone_treasure_box_info.h>
#include <protocol/mp_zone_item_pickup.h>
#include <protocol/mp_zone_dropitem_remove.h>
#include <protocol/mp_zone_object_collect.h>
#include <protocol/mp_zone_treasure_box_open.h>
#include <protocol/mp_zone_safety_state.h>
#include <protocol/mp_guild_create.h>
#include <protocol/mp_guild_join_request.h>
#include <protocol/mp_guild_accept_member.h>
#include <protocol/mp_guild_join_cancel.h>
#include <protocol/mp_guild_recommend.h>
#include <protocol/mp_guild_request_guild_list.h>
#include <protocol/mp_guild_member_list.h>
#include <protocol/mp_guild_info.h>
#include <protocol/mp_guild_ban.h>
#include <protocol/mp_guild_leave.h>
#include <protocol/mp_guild_change_member_grade.h>
#include <protocol/mp_guild_master_change_by_non_connected.h>
#include <protocol/mp_party_create.h>
#include <protocol/mp_party_info.h>
#include <protocol/mp_party_invite_request.h>
#include <protocol/mp_party_invite_refuse.h>
#include <protocol/mp_party_invite_agree.h>
#include <protocol/mp_party_enter_request.h>
#include <protocol/mp_party_enter_cancel.h>
#include <protocol/mp_party_enter_agree.h>
#include <protocol/mp_party_enter_refuse.h>
#include <protocol/mp_party_leave.h>
#include <protocol/mp_party_leave_alert_by_indun_kick.h>
#include <protocol/mp_party_pr.h>
#include <protocol/mp_party_destroy.h>
#include <protocol/mp_party_owner_change.h>
#include <protocol/mp_party_member_ban.h>
#include <protocol/mp_party_setup.h>
#include <protocol/mp_party_enter_request_list.h>
#include <protocol/mp_party_enter_requestors.h>
#include <protocol/mp_zone_vehicle.h>
#include <protocol/mp_zone_vehicle_state.h>
#include <protocol/mp_zone_character_level_up.h>
#include <protocol/mp_zone_character_expert_level_up.h>
#include <protocol/mp_skill_levelup.h>
#include <protocol/mp_skill_learn.h>
#include <protocol/mp_gm_kill_monster.h>
#include <protocol/mp_gm_damage_monster.h>
#include <protocol/mp_gm_getitem.h>
#include <protocol/mp_game_logout.h>
#include <protocol/mp_quest_accept.h>
#include <protocol/mp_quest_finish.h>
#include <protocol/mp_indun_siege_enter_test.h>
#include <protocol/mp_indun_play_count_request.h>
#include <protocol/mp_indun_prepare_request.h>
#include <protocol/mp_indun_prepare_enter.h>
#include <protocol/mp_indun_stage.h>
#include <protocol/mp_indun_stage_count.h>
#include <protocol/mp_indun_stage_complete.h>
#include <protocol/mp_indun_finish.h>
#include <protocol/mp_indun_leave.h>
#include <protocol/mp_indun_reward.h>
#include <protocol/mp_server_change.h>
#include <protocol/mp_redirect_complete.h>
#include <protocol/mp_zone_daily_content.h>
#include <protocol/mp_zone_fish.h>
#include <protocol/mp_zone_action_fish.h>
#include <protocol/mp_zone_action_state.h>
#include <protocol/mp_zone_boss_contribution.h>
#include <protocol/mp_zone_boss_dead.h>
#include <protocol/mp_inven_weight_expansion.h>
#include <protocol/mp_exchange_register.h>
#include <protocol/mp_exchange_register_cancel.h>
#include <protocol/mp_exchange_gold_withdraw.h>
#include <protocol/mp_exchange_buy.h>
#include <protocol/mp_exchange_item_withdraw.h>
#include <protocol/mp_chatting.h>
#include <protocol/mp_chat_command.h>
#include <protocol/mp_zone_trigger.h>
#include <protocol/mp_pk_setup.h>
#include <protocol/mp_mail_open.h>
#include <protocol/mp_mail_receive_item.h>
#include <protocol/mp_mail_delete.h>
#include <protocol/mp_mail_send.h>
#include <protocol/mp_meridians_levelup.h>
#include <protocol/mp_gm_check_attribute.h>
#include <protocol/mp_zone_move_error.h>
#include <protocol/mp_zone_object_return.h>
#include <protocol/mp_zone_object_return_teleport.h>
#include <protocol/mp_guild_change_join_condition.h>
#include <protocol/mp_guild_destroy.h>
#include <protocol/mp_guild_request_member_list.h>
#include <protocol/mp_guild_search.h>
#include <protocol/mp_repute_quest_finish_count_reset.h>
#include <protocol/mp_guild_donation.h>
#include <protocol/mp_guild_start_war.h>
#include <protocol/mp_guild_try_surrender.h>
#include <protocol/mp_guild_respond_surrender.h>
#include <protocol/mp_storage_open.h>
#include <protocol/mp_account_storage_buy.h>
#include <protocol/mp_storage_move.h>
#include <protocol/mp_storage_expand.h>
#include <protocol/mp_storage_goods_move.h>
#include <protocol/mp_attack_speed.h>
#include <protocol/mp_indun_auto_matching_complete.h>
#include <protocol/mp_indun_auto_matching_cancel.h>
#include <protocol/mp_indun_auto_matching_rematch.h>
#include <protocol/mp_personal_trade_refuse.h>
#include <protocol/mp_personal_trade_cancel.h>
#include <protocol/mp_party_vote_request.h>
#include <protocol/mp_party_vote_reply.h>
#include <protocol/mp_party_vote_result.h>
#include <protocol/mp_guild_war_list.h>
#include <protocol/mp_item_repair.h>
#include <protocol/mp_decrement_item_durability.h>
#include <protocol/mp_skill_passive_levelup.h>
#include <protocol/mp_zone_verify_move.h>
#include <protocol/mp_guild_alert_start_war.h>
#include <protocol/mp_guild_alert_end_war.h>
#include <protocol/mp_guild_alert_reject_surrender.h>
#include <protocol/mp_guild_alert_surrender.h>
#include <protocol/mp_guild_alert_join_request.h>
#include <protocol/mp_guild_alert_join_request_cancel.h>
#include <protocol/mp_guild_alert_join.h>
#include <protocol/mp_guild_alert_join_request_result.h>
#include <protocol/mp_guild_alert_leave.h>
#include <protocol/mp_guild_alert_ban_for_member.h>
#include <protocol/mp_guild_alert_ban.h>
#include <protocol/mp_guild_alert_change_grade.h>
#include <protocol/mp_guild_alert_change_nickname.h>
#include <protocol/mp_guild_add_exp.h>
#include <protocol/mp_guild_alert_add_exp.h>
#include <protocol/mp_party_teleport.h>
#include <protocol/mp_party_teleport_reply.h>
#include <protocol/mp_check_indun_enter_condition.h>
#include <protocol/mp_indun_enter_pay.h>
#include <protocol/mp_summon_recall.h>
#include <protocol/mp_siege_warfare_submit_tender.h>
#include <protocol/mp_siege_warfare_alert.h>
#include <protocol/mp_siege_warfare_alliance_request.h>
#include <protocol/mp_siege_warfare_alliance_cancel.h>
#include <protocol/mp_siege_warfare_alliance_response.h>
#include <protocol/mp_siege_warfare_alliance_kickout.h>
#include <protocol/mp_siege_warfare_alliance_withdrawal.h>
#include <protocol/mp_siege_warfare_atk_build_machine.h>
#include <protocol/mp_siege_warfare_atk_release_machine.h>
#include <protocol/mp_siege_warfare_def_build_machine.h>
#include <protocol/mp_siege_warfare_def_release_machine.h>
#include <protocol/mp_siege_tower_teleport.h>
#include <protocol/mp_castle_set_tax_rate.h>
#include <protocol/mp_castle_set_tax_distribution.h>
#include <protocol/mp_special_move_set.h>
#include <protocol/mp_skill_use.h>
#include <protocol/mp_guild_change_notice.h>
#include <protocol/mp_guild_alert_change_notice.h>
#include <protocol/mp_siege_warfare_time.h>
#include <protocol/mp_guild_learn_skill.h>
#include <protocol/mp_guild_alert_learn_skill.h>
#include <protocol/mp_guild_skill_list.h>
#include <protocol/mp_guild_alert_donation.h>
#include <protocol/mp_indun_stage_start.h>
#include <protocol/mp_guild_storage_material_list.h>
#include <protocol/mp_guild_item_donation.h>
#include <protocol/mp_chatting_system.h>
#include <protocol/mp_guild_storage_supply_list.h>
#include <protocol/mp_guild_storage_supply_get_item.h>
#include <protocol/mp_guild_storage_share_list.h>
#include <protocol/mp_guild_storage_share_insert_item.h>
#include <protocol/mp_guild_storage_share_request_get_item.h>
#include <protocol/mp_guild_storage_share_master_get_item.h>
#include <protocol/mp_guild_storage_share_alert_request_get_item.h>
#include <protocol/mp_guild_storage_share_result_get_item.h>
#include <protocol/mp_guild_storage_share_extend.h>
#include <protocol/mp_guild_storage_share_request_get_item_list.h>
#include <protocol/mp_castle_town_return.h>
#include <protocol/mp_enchant_stone_equip.h>
#include <protocol/mp_enchant_stone_slot_open.h>
#include <protocol/mp_enchant_stone_upgrade.h>
#include <protocol/mp_zone_siege_weapon_info.h>
#include <protocol/mp_zone_fixed_object_info.h>
#include <protocol/mp_zone_mercenary_info.h>
#include <protocol/mp_zone_siege_object_all.h>
#include <protocol/mp_castle_town_work.h>
#include <protocol/mp_castle_town_house_fire.h>
#include <protocol/mp_castle_town_arsenal_build.h>
#include <protocol/mp_castle_town_arsenal_build_donate.h>
#include <protocol/mp_guild_storage_treasure_list.h>
#include <protocol/mp_guild_storage_treasure_get_auction.h>
#include <protocol/mp_guild_storage_treasure_confirm_auction.h>
#include <protocol/mp_guild_storage_treasure_alert_lost_top_request.h>
#include <protocol/mp_guild_storage_treasure_alert_auction_finish.h>
#include <protocol/mp_guild_storage_treasure_request.h>
#include <protocol/mp_guild_dungeon_create.h>
#include <protocol/mp_siege_object_phase.h>
#include <protocol/mp_castle_town_arsenal_build_work_info.h>
#include <protocol/mp_castle_town_arsenal_build_end.h>
#include <protocol/mp_gm_guild_storage_treasure_insert_item.h>
#include <protocol/mp_castle_town_start_specialties.h>
#include <protocol/mp_castle_town_start_specialties_delivery.h>
#include <protocol/mp_gm_quest_clear.h>
#include <protocol/mp_gm_quest_clear_list.h>
#include <protocol/mp_gm_quest_accept.h>
#include <protocol/mp_guild_enemy_list.h>
#include <protocol/mp_heartbeat_check.h>
#include <protocol/mp_guild_town_boss_summon.h>
#include <protocol/mp_guild_register_master_order_quest.h>
#include <protocol/mp_guild_alert_register_master_order_quest.h>
#include <protocol/mp_guild_alert_finish_master_order_quest.h>
#include <protocol/mp_castle_town_start_dinner.h>
#include <protocol/mp_castle_town_dinner_get_item.h>
#include <protocol/mp_castle_town_hud_info.h>
#include <protocol/mp_pet_equip.h>
#include <protocol/mp_pet_feed.h>
#include <protocol/mp_zone_monster_respawn.h>
#include <protocol/mp_vehicle_equip.h>
#include <protocol/mp_vehicle_add.h>
#include <protocol/mp_vehicle_food.h>
#include <protocol/mp_vehicle_equip_item.h>
#include <protocol/mp_vehicle_expire.h>
#include <protocol/mp_randombox_open.h>
#include <protocol/mp_zone_sector_move.h>
#include <protocol/mp_zone_sector_teleport.h>
#include <protocol/mp_castle_dungeon_entrance_fee_change.h>
#include <protocol/mp_guild_alert_create_dungeon.h>
#include <protocol/mp_monster_run_away.h>
#include <protocol/mp_guild_alert_dungeon_enter.h>
#include <protocol/mp_title_equip.h>
#include <protocol/mp_pet_mix.h>
#include <protocol/mp_test_game_server.h>
#include <protocol/mp_guild_office_boss_summon_info.h>
#include <protocol/mp_siege_warfare_play_alert.h>
#include <protocol/mp_gm_get_pet.h>
#include <protocol/mp_gm_siege_indun_create.h>
#include <protocol/mp_pk_revenge_add.h>
#include <protocol/mp_pk_record_delete.h>
#include <protocol/mp_pk_revenge_delete.h>
#include <protocol/mp_pk_revenge_trace.h>
#include <protocol/mp_friend_request.h>
#include <protocol/mp_friend_delete.h>
#include <protocol/mp_friend_request_response.h>
#include <protocol/mp_friend_request_response_all.h>
#include <protocol/mp_friend_data_set.h>
#include <protocol/mp_pk_record_list_get.h>
#include <protocol/mp_pet_release_summon_broad.h>
#include <protocol/mp_mentor_register.h>
#include <protocol/mp_mentor_request.h>
#include <protocol/mp_mentor_buff_buy.h>
#include <protocol/mp_mentor_buff.h>
#include <protocol/mp_mentor_response.h>
#include <protocol/mp_title_add.h>
#include <protocol/mp_ranking_buff_reset.h>
#include <protocol/mp_achieve_add.h>
#include <protocol/mp_achieve_reward.h>
#include <protocol/mp_gm_title.h>
#include <protocol/mp_dictionary_add.h>
#include <protocol/mp_dictionary_get.h>
#include <protocol/mp_wanted_murder_register.h>
#include <protocol/mp_wanted_murder_reward.h>
#include <protocol/mp_wanted_murder_end_notify.h>
#include <protocol/mp_zone_teleport_save_area.h>
#include <protocol/mp_zone_teleport_save_area_delete.h>
#include <protocol/mp_zone_teleport_to_saved_area.h>
#include <protocol/mp_zone_teleport_fixed_point.h>
#include <protocol/mp_show_costume.h>
#include <protocol/mp_zone_teleport_view_point.h>
#include <protocol/mp_pk_revenge_result.h>
#include <protocol/mp_wanted_murder_number_of_uses.h>
#include <protocol/mp_guild_change_introduction.h>
#include <protocol/mp_guild_pr.h>
#include <protocol/mp_tutorial_complete.h>
#include <protocol/mp_guild_invite.h>
#include <protocol/mp_guild_invite_accept.h>
#include <protocol/mp_guild_invite_refusal.h>
#include <protocol/mp_guild_invite_notify.h>
#include <protocol/mp_guild_pr_notify.h>
#include <protocol/mp_teleport_arrive.h>
#include <protocol/mp_dictionary_reward_get.h>
#include <protocol/mp_dictionary_achieve_rate_get.h>
#include <protocol/mp_gm_dictionary_add.h>
#include <protocol/mp_dictionary_per_get.h>
#include <protocol/mp_achieve_get.h>
#include <protocol/mp_ai_game_login.h>
#include <protocol/mp_ai_service_start.h>
#include <protocol/mp_community_login.h>
#include <protocol/mp_dictionary_expire.h>
#include <protocol/mp_zone_teleport_ai_return.h>
#include <protocol/mp_gm_quest_initialization.h>
#include <protocol/mp_cash_shop_buy.h>
#include <protocol/mp_cash_shop_info.h>
#include <protocol/mp_cash_shop_cart_get.h>
#include <protocol/mp_gm_guild_add_exp.h>
#include <protocol/mp_gm_achieve_all_get.h>
#include <protocol/mp_gm_story_indun_clear.h>
#include <protocol/mp_server_time.h>
#include <protocol/mp_ai_setup_config.h>
#include <protocol/mp_gm_skill_expup.h>
#include <protocol/mp_cash_shop_exchange_reset.h>
#include <protocol/mp_cash_shop_limited_product.h>
#include <protocol/mp_indun_step_skip.h>
#include <protocol/mp_indun_alert_skip.h>
#include <protocol/mp_guild_shipwar_info.h>
#include <protocol/mp_guild_shipwar_request.h>
#include <protocol/mp_gm_guild_shipwar_state.h>
#include <protocol/mp_gm_siege_state.h>
#include <protocol/mp_guild_shipwar_team_info.h>
#include <protocol/mp_guild_shipwar_flag_notify.h>
#include <protocol/mp_guild_shipwar_situation.h>
#include <protocol/mp_gm_guild_shipwar_indun_create.h>
#include <protocol/mp_guild_shipwar_play_notify.h>
#include <protocol/mp_gm_super_armor.h>
#include <protocol/mp_red_dot_noti.h>
#include <protocol/mp_chatting_block.h>
#include <protocol/mp_chatting_block_list.h>
#include <protocol/mp_private_chatting_state.h>
#include <protocol/mp_cash_shop_daily_get.h>
#include <protocol/mp_town_rental_request.h>
#include <protocol/mp_town_alert.h>
#include <protocol/mp_town_rental_continuation.h>
#include <protocol/mp_schedule_info_list.h>
#include <protocol/mp_ai_setup_config_info.h>
#include <protocol/mp_transform_avatar.h>
#include <protocol/mp_release_avatar.h>
#include <protocol/mp_mentor_party_buff.h>
#include <protocol/mp_guild_shipwar_match_failed.h>
#include <protocol/mp_gm_guild_shipwar_play_start.h>
#include <protocol/mp_subscription_info.h>
#include <protocol/mp_dictionary_get_all.h>
#include <protocol/mp_npc_intimacy_add.h>
#include <protocol/mp_reset_treasurebox_owner.h>
#include <protocol/mp_revive_limit.h>
#include <protocol/mp_zone_teleport_exit.h>
#include <protocol/mp_zone_sector_info.h>
#include <protocol/mp_summon_pet.h>
#include <protocol/mp_summon_pet_broad.h>
#include <protocol/mp_siege_warfare_victory_character_info.h>
#include <protocol/mp_zone_call_point.h>
#include <protocol/mp_siege_kill_death.h>
#include <protocol/mp_special_move_gage.h>
#include <protocol/mp_enter_story_dungeon.h>
#include <protocol/mp_leave_story_dungeon.h>
#include <protocol/mp_trigger_story_dungeon.h>
#include <protocol/mp_move_story_dungeon.h>
#include <protocol/mp_gm_create_bot.h>
#include <protocol/mp_npc_intimacy_reward.h>
#include <protocol/mp_skill_start_story_dungeon.h>
#include <protocol/mp_object_state_story_dungeon.h>
#include <protocol/mp_zone_teleport_channel_move.h>
#include <protocol/mp_slot_option_make.h>
#include <protocol/mp_slot_option_select.h>
#include <protocol/mp_slot_upgrade.h>
#include <protocol/mp_change_pet_team.h>
#include <protocol/mp_npc_intimacy_reward_get.h>
#include <protocol/mp_friend_teleport.h>
#include <protocol/mp_treasureboxkey_charge.h>
#include <protocol/mp_skill_damage_story_dungeon.h>
#include <protocol/mp_guild_treasurebox_reward.h>
#include <protocol/mp_guard_pass_buy.h>
#include <protocol/mp_wanted_murder_target.h>
#include <protocol/mp_wanted_murder_trace.h>
#include <protocol/mp_seasonpass_change.h>
#include <protocol/mp_seasonpass_unlock.h>
#include <protocol/mp_seasonpass_reward.h>
#include <protocol/mp_seasonpass_challenge_complet.h>
#include <protocol/mp_seasonpass_challenge_update.h>
#include <protocol/mp_pk_alert_record_remove.h>
#include <protocol/mp_gm_avatar_get.h>
#include <protocol/mp_avatar_mix.h>
#include <protocol/mp_avatar_slot_set.h>
#include <protocol/mp_castle_owner_info.h>
#include <protocol/mp_guild_mark_change.h>
#include <protocol/mp_guild_alert_change_mark.h>
#include <protocol/mp_avatar_cool_time.h>
#include <protocol/mp_guild_buff_buy.h>
#include <protocol/mp_guild_gold_alert.h>
#include <protocol/mp_guild_dungeon_cumulative_damage.h>
#include <protocol/mp_mail_received.h>
#include <protocol/mp_gm_show_aggro.h>
#include <protocol/mp_gm_show_aggro_info.h>
#include <protocol/mp_gm_speed_attribute.h>
#include <protocol/mp_item_lock.h>
#include <protocol/mp_lord_bless_info.h>
#include <protocol/mp_lord_message.h>
#include <protocol/mp_lord_worship.h>
#include <protocol/mp_lord_bless_buff_use.h>
#include <protocol/mp_lord_bless_buff_info.h>
#include <protocol/mp_gm_castle_info_clear.h>
#include <protocol/mp_illusion_dungeon_time_charge.h>
#include <protocol/mp_secretvalley_alert.h>
#include <protocol/mp_secretvalley_info.h>
#include <protocol/mp_gm_secretvalley_state.h>
#include <protocol/mp_recovery_exp.h>
#include <protocol/mp_revive_list.h>
#include <protocol/mp_gm_reflection_add.h>
#include <protocol/mp_reflection_equip.h>
#include <protocol/mp_revive_request.h>
#include <protocol/mp_lord_bless_end_time.h>
#include <protocol/mp_zone_seal_device_use.h>
#include <protocol/mp_zone_seal_device_info.h>
#include <protocol/mp_gm_seal_device_reset.h>
#include <protocol/mp_blackiron_sell_regist.h>
#include <protocol/mp_blackiron_sell_info.h>
#include <protocol/mp_dimension_dungeon_info.h>
#include <protocol/mp_dimension_dungeon_piece.h>
#include <protocol/mp_get_character_rank.h>
#include <protocol/mp_party_member_enter_state.h>
#include <protocol/mp_demon_tower_info.h>
#include <protocol/mp_gm_demon_tower_spawn.h>
#include <protocol/mp_reflection_mix.h>
#include <protocol/mp_customizing_save.h>
#include <protocol/mp_guild_blackiron_alert.h>
#include <protocol/mp_demon_summon_info.h>
#include <protocol/mp_illusion_dungeon_time_out.h>
#include <protocol/mp_gm_add_guild_goods.h>
#include <protocol/mp_temp_reflection_change.h>
#include <protocol/mp_temp_reflection_confirm.h>
#include <protocol/mp_temp_reflection_get.h>
#include <protocol/mp_monster_phase_change.h>
#include <protocol/mp_zone_observer_mode.h>
#include <protocol/mp_arena_battle_match_regist.h>
#include <protocol/mp_arena_battle_match_regist_cancel.h>
#include <protocol/mp_gm_arena_battle_start.h>
#include <protocol/mp_arena_battle_score_board.h>
#include <protocol/mp_arena_battle_alert.h>
#include <protocol/mp_arena_battle_season_reward.h>
#include <protocol/mp_skill_force_reinforce.h>
#include <protocol/mp_mandala_rotation.h>
#include <protocol/mp_mandala_node_add.h>
#include <protocol/mp_mandala_reset.h>
#include <protocol/mp_mandala_node_levelup.h>
#include <protocol/mp_mandala_node_equip.h>
#include <protocol/mp_mandala_stone_upgrade.h>
#include <protocol/mp_mandala_node_reset.h>
#include <protocol/mp_indun_monarch_item_regist.h>
#include <protocol/mp_indun_monarch_state_alert.h>
#include <protocol/mp_indun_monarch_giveup.h>
#include <protocol/mp_guild_goods_update.h>
#include <protocol/mp_guild_goods_exchange.h>
#include <protocol/mp_indun_monarch_spawn_mob_info.h>
#include <protocol/mp_gm_profesion_update.h>
#include <protocol/mp_guild_alert_member_contribution_update.h>
#include <protocol/mp_street_stall_create.h>
#include <protocol/mp_street_stall_start.h>
#include <protocol/mp_street_stall_unmanned.h>
#include <protocol/mp_street_stall_start_result.h>
#include <protocol/mp_street_stall_create_cancel.h>
#include <protocol/mp_street_stall_stop.h>
#include <protocol/mp_street_stall_info.h>
#include <protocol/mp_guild_mark_alert.h>
#include <protocol/mp_contents_onoff_info.h>
#include <protocol/mp_party_auto_target_set.h>
#include <protocol/mp_party_auto_target_uid.h>
#include <protocol/mp_street_stall_sell_info.h>
#include <protocol/mp_street_stall_enter_info.h>
#include <protocol/mp_illusion_dungeon_info.h>
#include <protocol/mp_gm_get_vehicle.h>
#include <protocol/mp_street_stall_buy_open.h>
#include <protocol/mp_street_stall_buy.h>
#include <protocol/mp_street_stall_get_use_count.h>
#include <protocol/mp_update_max_hp_mp.h>
#include <protocol/mp_illusion_dungeon_info_get.h>
#include <protocol/mp_field_boss_kill.h>
#include <protocol/mp_character_fixed_battle.h>
#include <protocol/mp_auth_check.h>
#include <protocol/mp_session_auth.h>
#include <protocol/mp_session_type.h>
#include <protocol/mp_arena_join.h>
#include <protocol/mp_send_nickname_disable.h>
#include <protocol/mp_check_send_nickname_disable.h>
#include <protocol/mp_quest_reward_change.h>
#include <protocol/mp_arena_battle_matching_count.h>
#include <protocol/mp_indun_remaining_time.h>
#include <protocol/mp_arena_battle_revive_count.h>
#include <protocol/mp_temp_pet_change.h>
#include <protocol/mp_temp_pet_confirm.h>
#include <protocol/mp_temp_pet_get.h>
#include <protocol/mp_zone_client_request_object_info.h>
#include <protocol/mp_eclipse_center.h>
#include <protocol/mp_tonic_charge.h>
#include <protocol/mp_inven_size_change.h>
#include <protocol/mp_street_stall_pr.h>
#include <protocol/mp_street_stall_teleport.h>
#include <protocol/mp_game_login_inven.h>
#include <protocol/mp_game_login_inven_stone.h>
#include <protocol/mp_game_login_inven_essence.h>
#include <protocol/mp_game_login_mandala.h>
#include <protocol/mp_npc_shop_open.h>
#include <protocol/mp_guild_dungeon_enter_charge.h>
#include <protocol/mp_guild_alert_dungeon_info.h>
#include <protocol/mp_cash_limit_product_noti.h>
#include <protocol/mp_zone_client_request_object_state_info.h>
#include <protocol/mp_zone_client_option_setup.h>
#include <protocol/mp_occupationwar_tender_deposit.h>
#include <protocol/mp_occupationwar_tender_withdraw.h>
#include <protocol/mp_guild_shipwar_season_reward.h>
#include <protocol/mp_guild_shipwar_unearned_win_alarm.h>
#include <protocol/mp_darksteel_storage_darksteel_pay.h>
#include <protocol/mp_occupationwar_challenge_request_info.h>
#include <protocol/mp_occupationwar_challenge_request.h>
#include <protocol/mp_occupationwar_guild_info.h>
#include <protocol/mp_blood_dedicate_reward_change.h>
#include <protocol/mp_blood_dedicate_status.h>
#include <protocol/mp_blood_dedicate_zone_chatting.h>
#include <protocol/mp_blood_dedicate_worldboss_notify.h>
#include <protocol/mp_season_mandala_info_open.h>
#include <protocol/mp_season_mandala_reward_get.h>
#include <protocol/mp_season_mandala_reward_notify.h>

// #include <protocol/mp_gm_occupationwar_initialize.h>
// #include <protocol/mp_gm_occupationwar_set_schedule.h>
// #include <protocol/mp_gm_darksteel_storage_reload.h>
// #include <protocol/mp_gm_darksteel_storage_owner_update.h>
// #include <protocol/mp_gm_darksteel_storage_owner_info.h>
#include <protocol/mp_guild_search_custom.h>
#include <protocol/mp_enchant_stone_mix.h>
#include <protocol/mp_governance_staking.h>
#include <protocol/mp_governance_unstaking.h>
#include <protocol/mp_wallet_login.h>
#include <protocol/mp_wallet_linked_account.h>
#include <protocol/mp_get_contract_address.h>
#include <protocol/mp_trade_darksteelbox_to_token.h>
#include <protocol/mp_trade_token_to_darksteelbox.h>
#include <protocol/mp_approve_make_transaction.h>
#include <protocol/mp_approve_send_transaction.h>
#include <protocol/mp_global_exchange_register.h>
#include <protocol/mp_global_exchange_register_cancel.h>
#include <protocol/mp_global_exchange_buy.h>
#include <protocol/mp_global_exchange_gold_withdraw.h>
#include <protocol/mp_global_exchange_item_withdraw.h>
#include <protocol/mp_staking_make_tx.h>
#include <protocol/mp_staking_send_tx.h>
#include <protocol/mp_claim_make_tx.h>
#include <protocol/mp_claim_send_tx.h>
#include <protocol/mp_token_history_item_get.h>
#include <protocol/mp_global_party_governance_rank.h>
#include <protocol/mp_is_party_governance_decide_user.h>
#include <protocol/mp_global_party_governance_account_staking.h>
#include <protocol/mp_advertisement_reward.h>
#include <protocol/mp_server_relocation.h>
#include <protocol/mp_expert_request.h>
#include <protocol/mp_expert_equipment_info.h>
#include <protocol/mp_expert_equipment_unlock.h>
#include <protocol/mp_expert_equipment_equip.h>
#include <protocol/mp_expert_equipment_unequip.h>
#include <protocol/mp_expert_equipment_reinforce.h>
#include <protocol/mp_expert_equipment_enchant_stone_equip.h>
#include <protocol/mp_expert_equipment_enchant_stone_unequip.h>
#include <protocol/mp_expert_equipment_enchant_stone_upgrade.h>
#include <protocol/mp_expert_equipment_ability_ready.h>
#include <protocol/mp_mail_list.h>

#include <protocol/mp_equipment_awaken.h>
#include <protocol/mp_equipment_awaken_option_confirmed.h>

#include <protocol/mp_gate_castle_dungeon_info.h>
#include <protocol/mp_gate_castle_view_owner_info.h>
#include <protocol/mp_gate_castle_tax_with_member_info.h>
#include <protocol/mp_gate_siege_warfare_atk_machine_info.h>
#include <protocol/mp_gate_castle_town_info_by_guild_guid.h>
#include <protocol/mp_gate_castle_town_managing_info.h>
#include <protocol/mp_gate_castle_town_single_managing_info.h>
#include <protocol/mp_gate_castle_town_save_bag_info.h>
#include <protocol/mp_gate_castle_town_log.h>
#include <protocol/mp_gate_character_info_view.h>
#include <protocol/mp_gate_token_history_info_get.h>
#include <protocol/mp_gate_community_server_getinfo.h>
#include <protocol/mp_gate_contract_get_nonce.h>
#include <protocol/mp_gate_contract_get_address.h>
#include <protocol/mp_gate_contract_get_balance.h>
#include <protocol/mp_gate_contract_token_allowance.h>
#include <protocol/mp_gate_contract_get_limit.h>
#include <protocol/mp_gate_contract_add_exchagne.h>
#include <protocol/mp_gate_contract_get_staking_info.h>
#include <protocol/mp_gate_contract_get_balance_to_wdoller.h>
#include <protocol/mp_gate_world_boss_statking_player_info.h>
#include <protocol/mp_gate_coupon_use.h>
#include <protocol/mp_gate_friend_list.h>
#include <protocol/mp_gate_mentor_position.h>
#include <protocol/mp_gate_friend_request_count.h>
#include <protocol/mp_gate_friend_requested_list.h>
#include <protocol/mp_gate_game_option_save.h>
#include <protocol/mp_gate_game_option_select.h>
#include <protocol/mp_gate_game_setup_hash_select.h>
#include <protocol/mp_gate_game_setup_save.h>
#include <protocol/mp_gate_game_setup_select.h>
#include <protocol/mp_gate_guild_dungeon_member_damage.h>
#include <protocol/mp_gate_guild_dungeon_goods.h>
#include <protocol/mp_gate_guild_skill_goods.h>
#include <protocol/mp_gate_guild_share_storage_log.h>
#include <protocol/mp_gate_secretvalley_owner_info.h>
#include <protocol/mp_gate_guild_league_rank.h>
#include <protocol/mp_gate_guild_storage_history.h>
#include <protocol/mp_gate_mail_check.h>
#include <protocol/mp_gate_mail_list.h>
#include <protocol/mp_gate_mentor_info.h>
#include <protocol/mp_gate_mentor_list.h>
#include <protocol/mp_gate_mentor_rev_req_list.h>
#include <protocol/mp_gate_occupationwar_tender_history.h>
#include <protocol/mp_gate_darksteel_storage_info.h>
#include <protocol/mp_gate_darksteel_storage_history.h>
#include <protocol/mp_gate_darksteel_storage_darksteel_daily_pay.h>
#include <protocol/mp_gate_occupationwar_challenge_request_list.h>
#include <protocol/mp_gate_ranking_info.h>
#include <protocol/mp_gate_ranking_info_new.h>
#include <protocol/mp_gate_refinery_exchange_limit_check.h>
#include <protocol/mp_gate_search_around_party.h>
#include <protocol/mp_gate_search_category_party.h>
#include <protocol/mp_gate_search_user.h>
#include <protocol/mp_gate_shipwar_result_list.h>
#include <protocol/mp_gate_shipwar_result.h>
#include <protocol/mp_gate_siege_warfare_alliance_list.h>
#include <protocol/mp_gate_siege_warfare_alliance_receive_list.h>
#include <protocol/mp_gate_siege_warfare_guild_search.h>
#include <protocol/mp_gate_siegewarfare_observer_count.h>
#include <protocol/mp_gate_siege_warfare_tender_info.h>
#include <protocol/mp_gate_street_stall_sell_info.h>
#include <protocol/mp_gate_wanted_murder_list.h>
#include <protocol/mp_gate_wanted_murder_register_list.h>
#include <protocol/mp_gate_wanted_murder_reward_list.h>
#include <protocol/mp_gate_exchange_buybag_info.h>
#include <protocol/mp_gate_exchange_history.h>
#include <protocol/mp_gate_exchange_itemcount_all.h>
#include <protocol/mp_gate_exchange_itemcount_type.h>
#include <protocol/mp_gate_exchange_item_detail.h>
#include <protocol/mp_gate_exchange_itemid_reg_count_lists.h>
#include <protocol/mp_gate_exchange_itemid_lists.h>
#include <protocol/mp_gate_exchange_itemid_reinforce_count.h>
#include <protocol/mp_gate_exchange_itemid_reinforce_list.h>
#include <protocol/mp_gate_exchange_itemtype_count.h>
#include <protocol/mp_gate_exchange_marketprice.h>
#include <protocol/mp_gate_exchange_registrant_info.h>
#include <protocol/mp_gate_field_boss_regist_info.h>
#include <protocol/mp_gate_event_info.h>
#include <protocol/mp_gate_event_reward.h>
#include <protocol/mp_gate_global_exchange_buybag_info.h>
#include <protocol/mp_gate_global_exchange_history.h>
#include <protocol/mp_gate_global_exchange_itemcount_all.h>
#include <protocol/mp_gate_global_exchange_itemcount_type.h>
#include <protocol/mp_gate_global_exchange_item_detail.h>
#include <protocol/mp_gate_global_exchange_itemid_reg_count_lists.h>
#include <protocol/mp_gate_global_exchange_itemid_lists.h>
#include <protocol/mp_gate_global_exchange_itemid_reinforce_count.h>
#include <protocol/mp_gate_global_exchange_itemid_reinforce_list.h>
#include <protocol/mp_gate_global_exchange_itemtype_count.h>
#include <protocol/mp_gate_global_exchange_marketprice.h>
#include <protocol/mp_gate_global_exchange_registrant_info.h>
#include <protocol/mp_gate_cash_shop_info.h>
#include <protocol/mp_gate_contents_onoff_list.h>
#include <protocol/mp_gate_pay_start.h>
#include <protocol/mp_gate_pay_verify.h>
#include <protocol/mp_gate_pre_verify.h>
#include <protocol/mp_gate_promo_verify.h>
#include <protocol/mp_gate_cash_shop_item_list.h>
#include <protocol/mp_gate_lobby_character_create.h>
#include <protocol/mp_gate_lobby_character_delete.h>
#include <protocol/mp_gate_lobby_character_delete_cancel.h>
#include <protocol/mp_gate_lobby_character_select.h>
#include <protocol/mp_gate_lobby_gameplaylogin.h>
#include <protocol/mp_gate_lobby_gamelogin_await_cancel.h>
#include <protocol/mp_gate_get_available_font_list.h>
#include <protocol/mp_gate_channel_status.h>
#include <protocol/mp_gate_channel_full_check.h>
#include <protocol/mp_gate_arena_battle_ranking.h>
#include <protocol/mp_gate_arena_battle_info.h>
#include <protocol/mp_gate_arena_battle_result_list.h>
#include <protocol/mp_gate_arena_battle_result.h>
#include <protocol/mp_gate_guildshipwar_season_reward.h>
#include <protocol/mp_gate_world_boss_statking_board_info.h>
#include <protocol/mp_gate_occupationwar_statking_board_info.h>
#include <protocol/mp_gate_occupationwar_schedule_info.h>
#include <protocol/mp_gate_world_boss_linked_wallet_info.h>
#include <protocol/mp_gate_worldboard_guild_league_rank.h>
#include <protocol/mp_gate_worldboard_shipwar_result_list.h>
#include <protocol/mp_gate_worldboard_shipwar_result.h>
#include <protocol/mp_gate_get_all_balance_swap_token.h>
#include <protocol/mp_gate_wemix_pay_start.h>
#include <protocol/mp_gate_wemix_pay_end.h>
#include <protocol/mp_gate_dogma_pay_start.h>
#include <protocol/mp_gate_dogma_pay_end.h>
#include <protocol/mp_gate_dogma_get_oracle.h>
#include <protocol/mp_gate_get_wemix_amount.h>
#include <protocol/mp_gate_get_wemix_history.h>
#include <protocol/mp_gate_advertisement_info.h>
#include <protocol/mp_gate_advertisement_exp_restore.h>
#include <protocol/mp_gate_advertisement_reward.h>
#include <protocol/mp_gate_advertisement_event_reward.h>
#include <protocol/mp_gate_lobby_player_character_select.h>
#include <protocol/mp_gate_lobby_player_character_delete.h>
#include <protocol/mp_gate_community_login.h>
#include <protocol/mp_gate_chatting.h>
#include <protocol/mp_gate_chatting_block.h>
#include <protocol/mp_gate_chatting_block_list.h>
#include <protocol/mp_gate_private_chatting_state.h>
#include <protocol/mp_gate_server_relocation_list.h>
#include <protocol/mp_gate_dimension_dungeon_schedule.h>
#include <protocol/mp_gate_blood_dedicate_worldboss_status.h>
#include <protocol/mp_guild_member_pvp_info.h>
#include <protocol/mp_guild_ally_request_accept.h>
#include <protocol/mp_guild_ally_request_deny.h>
#include <protocol/mp_guild_ally_request_regist.h>
#include <protocol/mp_guild_ally_list.h>
#include <protocol/mp_guild_ally_request_list.h>
#include <protocol/mp_guild_search_by_guid.h>
#include <protocol/mp_guild_ally_cancel.h>
#include <protocol/mp_guild_ally_alert.h>
#include <protocol/mp_guild_ally_detail_info.h>
#include <protocol/mp_guild_member_location.h>
#include <protocol/mp_guild_member_pk_death_alert.h>
#include <protocol/mp_boss_dungeon_clear.h>
#include <protocol/mp_gate_dungeon_ranking_info.h>
#include <protocol/mp_boss_dungeon_start_time.h>
#include <protocol/mp_restore_item_list.h>
#include <protocol/mp_restore_compose_list.h>
#include <protocol/mp_restore_item.h>
#include <protocol/mp_restore_compose.h>
#include <protocol/mp_restore_event_noti.h>
#include <protocol/mp_pet_team_equip.h>
#pragma endregion mp


#pragma region mps

#include <protocol/struct/mps_login_account.h>
#include <protocol/struct/mps_login_character.h>
#include <protocol/struct/mps_login_server_group_info.h>
#include <protocol/struct/mps_server_info.h>
#include <protocol/struct/mps_player.h>
#include <protocol/struct/mps_player_character.h>
#include <protocol/struct/mps_list_meridians.h>
#include <protocol/struct/mps_groupid_info.h>
#include <protocol/struct/mps_meridians_back.h>
#include <protocol/struct/mps_meridians.h>
#include <protocol/struct/mps_zone_object_info.h>
#include <protocol/struct/mps_zone_treasure_box_info.h>
#include <protocol/struct/mps_zone_info.h>
#include <protocol/struct/mps_character_stat.h>
#include <protocol/struct/mps_inventory.h>
#include <protocol/struct/mps_questbook.h>
#include <protocol/struct/mps_quest_history.h>
#include <protocol/struct/mps_quest.h>
#include <protocol/struct/mps_repute_quest.h>
#include <protocol/struct/mps_quest_area.h>
#include <protocol/struct/mps_skillbook.h>
#include <protocol/struct/mps_skill.h>
#include <protocol/struct/mps_game_setup.h>
#include <protocol/struct/mps_profesion.h>
#include <protocol/struct/mps_daily_content.h>
#include <protocol/struct/mps_vector.h>
#include <protocol/struct/mps_vector2d.h>
#include <protocol/struct/mps_zone_player_info.h>
#include <protocol/struct/mps_zone_monster_info.h>
#include <protocol/struct/mps_zone_npc_info.h>
#include <protocol/struct/mps_zone_character_minion.h>
#include <protocol/struct/mps_buff.h>
#include <protocol/struct/mps_ability_value.h>
#include <protocol/struct/mps_zone_collect_info.h>
#include <protocol/struct/mps_zone_drop_item_info.h>
#include <protocol/struct/mps_drop_item_info.h>
#include <protocol/struct/mps_item.h>
#include <protocol/struct/mps_item_option_update.h>
#include <protocol/struct/mps_item_option.h>
#include <protocol/struct/mps_global_exchange_rollback_item.h>
#include <protocol/struct/mps_enchant_option.h>
#include <protocol/struct/mps_list_int64.h>
#include <protocol/struct/mps_skill_list.h>
#include <protocol/struct/mps_list_quest.h>
#include <protocol/struct/mps_repute_quest_list.h>
#include <protocol/struct/mps_target_info.h>
#include <protocol/struct/mps_field_boss.h>
#include <protocol/struct/mps_boss_contribution.h>
#include <protocol/struct/mps_character_ability_stat.h>
#include <protocol/struct/mps_character_ability.h>
#include <protocol/struct/mps_update_goods.h>
#include <protocol/struct/mps_update_goods_list.h>
#include <protocol/struct/mps_item_count_update.h>
#include <protocol/struct/mps_equip_info.h>
#include <protocol/struct/mps_equip_info_list.h>
#include <protocol/struct/mps_update_exp.h>
#include <protocol/struct/mps_item_add.h>
#include <protocol/struct/mps_gameitem_update.h>
#include <protocol/struct/mps_stat_update.h>
#include <protocol/struct/mps_damage_list.h>
#include <protocol/struct/mps_damage_result.h>
#include <protocol/struct/mps_item_iuid_list.h>
#include <protocol/struct/mps_item_iuid.h>
#include <protocol/struct/mps_slot.h>
#include <protocol/struct/mps_slot_list.h>
#include <protocol/struct/mps_party_member_enter_state.h>
#include <protocol/struct/mps_party_member.h>
#include <protocol/struct/mps_party_member_base.h>
#include <protocol/struct/mps_party_base.h>
#include <protocol/struct/mps_party_info.h>
#include <protocol/struct/mps_comm_equip.h>
#include <protocol/struct/mps_comm_equip_list.h>
#include <protocol/struct/mps_comm_character.h>
#include <protocol/struct/mps_equip_list.h>
#include <protocol/struct/mps_exchange_item_info.h>
#include <protocol/struct/mps_global_exchange_item_info.h>
#include <protocol/struct/mps_exchange_item_count.h>
#include <protocol/struct/mps_exchange_item_count_list.h>
#include <protocol/struct/mps_exchange_reg_item.h>
#include <protocol/struct/mps_exchange_reg_item_list.h>
#include <protocol/struct/mps_exchange_reg_item_type.h>
#include <protocol/struct/mps_exchange_reg_item_type_list.h>
#include <protocol/struct/mps_global_exchange_sell_item.h>
#include <protocol/struct/mps_global_exchange_sell_item_list.h>
#include <protocol/struct/mps_global_exchange_sell_item_type.h>
#include <protocol/struct/mps_global_exchange_sell_item_type_list.h>
#include <protocol/struct/mps_exchange_reinforce_count.h>
#include <protocol/struct/mps_global_exchange_reinforce_count.h>
#include <protocol/struct/mps_exchange_reinforce_count_list.h>
#include <protocol/struct/mps_global_exchange_reinforce_count_list.h>
#include <protocol/struct/mps_exchange_market_price.h>
#include <protocol/struct/mps_global_exchange_market_price.h>
#include <protocol/struct/mps_exchange_registrant_item.h>
#include <protocol/struct/mps_exchange_registrant_list.h>
#include <protocol/struct/mps_global_exchange_registrant_item.h>
#include <protocol/struct/mps_global_exchange_registrant_list.h>
#include <protocol/struct/mps_exchange_buybag_item.h>
#include <protocol/struct/mps_exchange_buybag_list.h>
#include <protocol/struct/mps_global_exchange_purchase_item.h>
#include <protocol/struct/mps_global_exchange_purchase_item_list.h>
#include <protocol/struct/mps_make_result.h>
#include <protocol/struct/mps_make_result_list.h>
#include <protocol/struct/mps_profesion_update.h>
#include <protocol/struct/mps_enchant_option_list.h>
#include <protocol/struct/mps_enchant_options.h>
#include <protocol/struct/mps_enchant_option_result.h>
#include <protocol/struct/mps_guild_member.h>
#include <protocol/struct/mps_guild.h>
#include <protocol/struct/mps_map_discovery.h>
#include <protocol/struct/mps_item_id.h>
#include <protocol/struct/mps_mail_item.h>
#include <protocol/struct/mps_mail.h>
#include <protocol/struct/mps_equip_item_info.h>
#include <protocol/struct/mps_character.h>
#include <protocol/struct/mps_lobby_player.h>
#include <protocol/struct/mps_lobby_character.h>
#include <protocol/struct/mps_lobby_gameinfo.h>
#include <protocol/struct/mps_lobby_gameplayinfo.h>
#include <protocol/struct/mps_lobby_game_info.h>
#include <protocol/struct/mps_login_lobby_info.h>
#include <protocol/struct/mps_enter_character.h>
#include <protocol/struct/mps_exchange_context.h>
#include <protocol/struct/mps_object_list.h>
#include <protocol/struct/mps_db_buff.h>
#include <protocol/struct/mps_guild_request_member.h>
#include <protocol/struct/mps_account_storage.h>
#include <protocol/struct/mps_storage_move_update.h>
#include <protocol/struct/mps_storage_move_goods.h>
#include <protocol/struct/mps_storage_move_insert.h>
#include <protocol/struct/mps_storage_move.h>
#include <protocol/struct/mps_indun_play_count_request.h>
#include <protocol/struct/mps_trade_info.h>
#include <protocol/struct/mps_guild_war.h>
#include <protocol/struct/mps_item_durability.h>
#include <protocol/struct/mps_list_item_durability.h>
#include <protocol/struct/mps_dungeon.h>
#include <protocol/struct/mps_list_dungeon.h>
#include <protocol/struct/mps_decrement_item_durability.h>
#include <protocol/struct/mps_item_pickup_info.h>
#include <protocol/struct/mps_item_pickup.h>
#include <protocol/struct/mps_siege_warfare_info.h>
#include <protocol/struct/mps_siege_warfare_alliance_info.h>
#include <protocol/struct/mps_siege_warfare_request_alliance_info.h>
#include <protocol/struct/mps_siege_warfare_alliance.h>
#include <protocol/struct/mps_castle_info.h>
#include <protocol/struct/mps_castle_tax_member.h>
#include <protocol/struct/mps_siege_machine.h>
#include <protocol/struct/mps_combo_info_back.h>
#include <protocol/struct/mps_list_combo.h>
#include <protocol/struct/mps_siege_warfare_time_info.h>
#include <protocol/struct/mps_combo_info.h>
#include <protocol/struct/mps_combo_ability.h>
#include <protocol/struct/mps_enemy_error.h>
#include <protocol/struct/mps_castle_town_all_info.h>
#include <protocol/struct/mps_castle_town_info.h>
#include <protocol/struct/mps_castle_town_info_detail.h>
#include <protocol/struct/mps_castle_view_owner_info.h>
#include <protocol/struct/mps_castle_town_building_info.h>
#include <protocol/struct/mps_castle_town_info_with_guild.h>
#include <protocol/struct/mps_castle_town_work.h>
#include <protocol/struct/mps_guild_storage_share_request_get_item.h>
#include <protocol/struct/mps_guild_storage_share_item.h>
#include <protocol/struct/mps_guild_storage_history.h>
#include <protocol/struct/mps_castle_town_guild_tender.h>
#include <protocol/struct/mps_castle_town_tender_info.h>
#include <protocol/struct/mps_enchant_stone.h>
#include <protocol/struct/mps_enchant_stone_update.h>
#include <protocol/struct/mps_zone_siege_weapon_info.h>
#include <protocol/struct/mps_zone_fixed_object_info.h>
#include <protocol/struct/mps_zone_mercenary_info.h>
#include <protocol/struct/mps_castle_town_arsenal_work.h>
#include <protocol/struct/mps_guild_storage_treasure_auction.h>
#include <protocol/struct/mps_guild_storage_treasure_request.h>
#include <protocol/struct/mps_guild_storage_treasure_item.h>
#include <protocol/struct/mps_guild_storage_treasure_my_request.h>
#include <protocol/struct/mps_guild_dungeon_info.h>
#include <protocol/struct/mps_guild_castle_info.h>
#include <protocol/struct/mps_guild_town_info.h>
#include <protocol/struct/mps_castle_town_managing_info.h>
#include <protocol/struct/mps_castle_town_character_specialties_work.h>
#include <protocol/struct/mps_castle_town_specialties_work.h>
#include <protocol/struct/mps_vehicle.h>
#include <protocol/struct/mps_list_db_buff.h>
#include <protocol/struct/mps_guild_master_order_quest.h>
#include <protocol/struct/mps_castle_town_dinner_work.h>
#include <protocol/struct/mps_pet_info.h>
#include <protocol/struct/mps_vehicle_equip_item.h>
#include <protocol/struct/mps_list_vehicle_equip_item.h>
#include <protocol/struct/mps_guild_dungeon_member_damage.h>
#include <protocol/struct/mps_guild_dungeon_member_damage_info.h>
#include <protocol/struct/mps_castle_dungeon_info.h>
#include <protocol/struct/mps_list_pet_info.h>
#include <protocol/struct/mps_reward_value.h>
#include <protocol/struct/mps_list_reward_value.h>
#include <protocol/struct/mps_pk_record.h>
#include <protocol/struct/mps_pk_revenge.h>
#include <protocol/struct/mps_title.h>
#include <protocol/struct/mps_dictionary_info.h>
#include <protocol/struct/mps_character_simple_info.h>
#include <protocol/struct/mps_friend_info.h>
#include <protocol/struct/mps_mentor.h>
#include <protocol/struct/mps_list_mentor.h>
#include <protocol/struct/mps_contents_onoff_data.h>
#include <protocol/struct/mps_contents_onoff_info.h>
#include <protocol/struct/mps_ranking_history.h>
#include <protocol/struct/mps_ranking_info.h>
#include <protocol/struct/mps_ranking_history_new.h>
#include <protocol/struct/mps_game_option.h>
#include <protocol/struct/mps_character_dictionary_stat.h>
#include <protocol/struct/mps_teleport_area.h>
#include <protocol/struct/mps_obtain_pet_info.h>
#include <protocol/struct/mps_simple_pk_revenge_info.h>
#include <protocol/struct/mps_wanted_murder.h>
#include <protocol/struct/mps_wanted_murder_list.h>
#include <protocol/struct/mps_list_dictionary_info.h>
#include <protocol/struct/mps_achieve_rate_info.h>
#include <protocol/struct/mps_dictionary_per_info.h>
#include <protocol/struct/mps_item_update.h>
#include <protocol/struct/mps_cart_item.h>
#include <protocol/struct/mps_cash_shop_buy_count.h>
#include <protocol/struct/mps_cash_info.h>
#include <protocol/struct/mps_exchange_search_info.h>
#include <protocol/struct/mps_exchange_search_item.h>
#include <protocol/struct/mps_exchange_search_item_list.h>
#include <protocol/struct/mps_global_exchange_search_item.h>
#include <protocol/struct/mps_global_exchange_search_item_list.h>
#include <protocol/struct/mps_ai_setup_config.h>
#include <protocol/struct/mps_cash_exchange_product.h>
#include <protocol/struct/mps_cash_limited_product.h>
#include <protocol/struct/mps_character_situation.h>
#include <protocol/struct/mps_guild_shipwar_situation.h>
#include <protocol/struct/mps_guild_league_info.h>

#include <protocol/struct/mps_cash_package_product.h>
#include <protocol/struct/mps_ability_calc_option.h>
#include <protocol/struct/mps_dic_stat.h>
#include <protocol/struct/mps_character_info_view.h>
#include <protocol/struct/mps_schedule_info.h>
#include <protocol/struct/mps_castle_town_log.h>
#include <protocol/struct/mps_zone_player_avatar_info.h>
#include <protocol/struct/mps_avatar_info.h>
#include <protocol/struct/mps_pickup_info.h>
#include <protocol/struct/mps_subscription_info.h>
#include <protocol/struct/mps_dictionary_count_info.h>
#include <protocol/struct/mps_sector_info.h>
#include <protocol/struct/mps_siege_result_score.h>
#include <protocol/struct/mps_channel_status_info.h>
#include <protocol/struct/mps_reward_info.h>
#include <protocol/struct/mps_event_info.h>
#include <protocol/struct/mps_reward_pet_info.h>
#include <protocol/struct/mps_wanted_murder_info.h>
#include <protocol/struct/mps_wanted_murder_info_list.h>
#include <protocol/struct/mps_wanted_murder_register_info.h>
#include <protocol/struct/mps_wanted_murder_register_info_list.h>
#include <protocol/struct/mps_wanted_murder_reward_info.h>
#include <protocol/struct/mps_wanted_murder_reward_info_list.h>
#include <protocol/struct/mps_seasonpass_challenge.h>
#include <protocol/struct/mps_seasonpass.h>
#include <protocol/struct/mps_avatar.h>
#include <protocol/struct/mps_obtain_avatar.h>
#include <protocol/struct/mps_received_mail.h>
#include <protocol/struct/mps_lord_statue_info.h>
#include <protocol/struct/mps_show_aggro_info.h>
#include <protocol/struct/mps_lord_bless_buff.h>
#include <protocol/struct/mps_lord_bless_info.h>
#include <protocol/struct/mps_illusion_dungeon.h>
#include <protocol/struct/mps_revive.h>
#include <protocol/struct/mps_secretvalley_owner_info.h>
#include <protocol/struct/mps_seal_device_info.h>
#include <protocol/struct/mps_reflection.h>
#include <protocol/struct/mps_obtain_reflection.h>
#include <protocol/struct/mps_temp_reflection.h>
#include <protocol/struct/mps_arena_character.h>
#include <protocol/struct/mps_arena_battle_ranking_info.h>
#include <protocol/struct/mps_mandala_node_info.h>
#include <protocol/struct/mps_mandala_layer_info.h>
#include <protocol/struct/mps_mandala_layer_rotate.h>
#include <protocol/struct/mps_special_move.h>
#include <protocol/struct/mps_reflection_change_skill.h>
#include <protocol/struct/mps_guild_league_rank.h>
#include <protocol/struct/mps_guild_member_look_info.h>
#include <protocol/struct/mps_guild_treasurebox_reward_item.h>
#include <protocol/struct/mps_guild_share_storage_log.h>
#include <protocol/struct/mps_guild_goods.h>
#include <protocol/struct/mps_guild_goods_info.h>
#include <protocol/struct/mps_guild_ally_info.h>
#include <protocol/struct/mps_guild_ally_request_info.h>
#include <protocol/struct/mps_other_guild_info.h>
#include <protocol/struct/mps_guild_ally_simple_info.h>
#include <protocol/struct/mps_street_stall_info.h>
#include <protocol/struct/mps_street_stall_object_info.h>
#include <protocol/struct/mps_street_stall_product_info.h>
#include <protocol/struct/mps_street_stall_owner_stat.h>
#include <protocol/struct/mps_street_stall_log.h>
#include <protocol/struct/mps_street_stall_item_reinforce.h>
#include <protocol/struct/mps_street_stall_item_reinforce_result.h>
#include <protocol/struct/mps_street_stall_item_luck_reinforce.h>
#include <protocol/struct/mps_street_stall_item_luck_reinforce_result.h>
#include <protocol/struct/mps_street_stall_item_enchant_option_make.h>
#include <protocol/struct/mps_street_stall_item_enchant_option_make_result.h>
#include <protocol/struct/mps_street_stall_fees.h>
#include <protocol/struct/mps_server_inspection.h>
#include <protocol/struct/mps_title_info.h>
#include <protocol/struct/mps_achieve_info.h>
#include <protocol/struct/mps_quest_reward.h>
#include <protocol/struct/mps_street_stall_item_enchant_option_change.h>
#include <protocol/struct/mps_street_stall_item_enchant_option_change_result.h>
#include <protocol/struct/mps_arena_character_season_info.h>
#include <protocol/struct/mps_temp_pet.h>
#include <protocol/struct/mps_exchange_item_history.h>
#include <protocol/struct/mps_global_exchange_item_history.h>
#include <protocol/struct/mps_exchange_history.h>
#include <protocol/struct/mps_global_exchange_history.h>
#include <protocol/struct/mps_title_send_info.h>
#include <protocol/struct/mps_npc_buy_count.h>
#include <protocol/struct/mps_decompose_item.h>
#include <protocol/struct/mps_cash_shop_item.h>
#include <protocol/struct/mps_contents_onoff.h>
#include <protocol/struct/mps_contents_onoff_list.h>
#include <protocol/struct/mps_darksteel_box_keep.h>
#include <protocol/struct/mps_darksteel_box_keep_list.h>
#include <protocol/struct/mps_darksteel_box_keep_server.h>
#include <protocol/struct/mps_darksteel_box_keep_server_info.h>
#include <protocol/struct/mps_darksteel_storage_info.h>
#include <protocol/struct/mps_darksteel_storage_owner_info.h>
#include <protocol/struct/mps_darksteel_storage_history.h>
#include <protocol/struct/mps_darksteel_storage_history_list.h>
#include <protocol/struct/mps_darksteel_storage_daily_pay_info.h>
#include <protocol/struct/mps_darksteel_storage_daily_pay_info_list.h>
#include <protocol/struct/mps_occupationwar_challenge_guild_info.h>
#include <protocol/struct/mps_occupationwar_guild_info.h>
#include <protocol/struct/mps_occupationwar_schedule.h>
#include <protocol/struct/mps_occupationwar_schedule_info.h>
#include <protocol/struct/mps_occupationwar_schedule_info_list.h>
#include <protocol/struct/mps_occupationwar_schedule_view.h>
#include <protocol/struct/mps_occupationwar_challenge_rank.h>
#include <protocol/struct/mps_occupationwar_war_info.h>
#include <protocol/struct/mps_region_status_server.h>
#include <protocol/struct/mps_enchant_strone_result.h>
#include <protocol/struct/mps_make_item.h>
#include <protocol/struct/mps_boss_governance_server_info_personal.h>
#include <protocol/struct/mps_boss_governance_server_info_total.h>
#include <protocol/struct/mps_boss_governance_server_info_list.h>
#include <protocol/struct/mps_boss_governance_deposit_withdraw_history.h>
#include <protocol/struct/mps_available_font.h>
#include <protocol/struct/mps_global_staking_info.h>
#include <protocol/struct/mps_global_staking_info_list.h>
#include <protocol/struct/mps_boss_governance_summon_onoff.h>
#include <protocol/struct/mps_boss_governance_server_info_personal_list.h>
#include <protocol/struct/mps_governance_server_info_total.h>
#include <protocol/struct/mps_token_history.h>
#include <protocol/struct/mps_token_history_info.h>
#include <protocol/struct/mps_party_governance_rank.h>
#include <protocol/struct/mps_token_info.h>
#include <protocol/struct/mps_token_balance.h>
#include <protocol/struct/mps_purchase_info.h>
#include <protocol/struct/mps_party_governance_decide_info.h>
#include <protocol/struct/mps_wemix_shop_history.h>
#include <protocol/struct/mps_advertisement.h>
#include <protocol/struct/mps_advertisement_event.h>
#include <protocol/struct/mps_character_advertisement.h>
#include <protocol/struct/mps_server_relocation_list.h>
#include <protocol/struct/mps_monarch_info.h>
#include <protocol/struct/mps_dimension_dungeon_piece_info.h>
#include <protocol/struct/mps_blood_dedicate_status_info.h>
#include <protocol/struct/mps_expert_equipment_info.h>
#include <protocol/struct/mps_boss_dungeon_reward.h>
#include <protocol/struct/mps_restore_item.h>
#include <protocol/struct/mps_restore_compose.h>
#include <protocol/struct/mps_restore_noti.h>
#include <protocol/struct/mps_paid_acc_reinforce_request_data.h>
#include <protocol/struct/mps_paid_acc_reinforce_result_data.h>

#pragma endregion mps




